# Generated by Django 6.1 on 2026-08-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalieDetectee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_anomalie', models.CharField(choices=[('ECART_STOCK', 'Écart de stock non justifié'), ('ECART_CAISSE', 'Écart de caisse non justifié'), ('DEPASSEMENT_MATIERE', 'Dépassement de sortie matière'), ('LOT_NON_LIBERE_VENDU', "Tentative de vente d'un lot non libéré"), ('COMMANDE_CLIENT_BLOQUE', 'Commande sur client bloqué'), ('AUTRE', 'Autre anomalie')], max_length=30, verbose_name="Type d'anomalie")),
                ('module_source', models.CharField(max_length=50, verbose_name='Module source')),
                ('description', models.TextField(verbose_name='Description')),
                ('statut', models.CharField(choices=[('DETECTEE', 'Détectée'), ('EN_TRAITEMENT', 'En traitement'), ('TRAITEE', 'Traitée'), ('IGNOREE', 'Ignorée (justifiée)')], default='DETECTEE', max_length=20, verbose_name='Statut')),
                ('date_detection', models.DateTimeField(auto_now_add=True, verbose_name='Date de détection')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
            ],
            options={
                'verbose_name': 'Anomalie détectée',
                'verbose_name_plural': 'Anomalies détectées',
                'ordering': ['-date_detection'],
            },
        ),
        migrations.CreateModel(
            name='Cloture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(help_text='Format AAAA-MM ou AAAA', max_length=20, verbose_name='Période')),
                ('type_cloture', models.CharField(choices=[('MENSUELLE', 'Mensuelle'), ('ANNUELLE', 'Annuelle')], max_length=15, verbose_name='Type de clôture')),
                ('date_cloture', models.DateTimeField(auto_now_add=True, verbose_name='Date de clôture')),
            ],
            options={
                'verbose_name': 'Clôture',
                'verbose_name_plural': 'Clôtures',
            },
        ),
        migrations.CreateModel(
            name='ExportComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_export', models.CharField(choices=[('VENTES', 'Ventes'), ('ENCAISSEMENTS', 'Encaissements'), ('ACHATS', 'Achats'), ('JOURNAL', 'Journal comptable')], max_length=20, verbose_name="Type d'export")),
                ('periode_debut', models.DateField(verbose_name='Début de période')),
                ('periode_fin', models.DateField(verbose_name='Fin de période')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='exports_comptables/', verbose_name='Fichier généré')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
            ],
            options={
                'verbose_name': 'Export comptable',
                'verbose_name_plural': 'Exports comptables',
                'ordering': ['-date_generation'],
            },
        ),
    ]
