# Generated by Django 6.1 on 2026-09-30 13:02

import django.db.models.deletion
from django.db import migrations, models


def comptes_par_defaut(apps, schema_editor):
    """Plan SYSCOHADA révisé proposé par défaut, modifiable ensuite par la Comptabilité/DAF."""
    from apps.comptabilite.models import COMPTES_PAR_DEFAUT
    CompteParametre = apps.get_model("comptabilite", "CompteParametre")
    for cle, numero in COMPTES_PAR_DEFAUT.items():
        CompteParametre.objects.get_or_create(cle=cle, defaults={"numero": numero})


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteParametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(choices=[('CLIENTS', 'Clients'), ('FOURNISSEURS', 'Fournisseurs'), ('VENTES_PRODUITS_FINIS', "Ventes de produits finis (si l'article n'a pas de compte de vente)"), ('TVA_COLLECTEE', 'TVA facturée sur ventes'), ('ACCISES', "Droits d'accises"), ('CENTIMES_ADDITIONNELS', 'Centimes additionnels'), ('RABAIS_ACCORDES', 'Rabais, remises, ristournes accordés (avoirs)'), ('ACHATS_MATIERES', 'Achats de matières premières et fournitures'), ('CAISSE', 'Caisse (espèces)'), ('BANQUE', 'Banque (virement, chèque)'), ('MOBILE_MONEY', 'Mobile Money'), ('CHARGES_DIVERSES', 'Charges diverses (décaissements)')], max_length=30, unique=True, verbose_name='Rôle')),
                ('numero', models.CharField(max_length=20, verbose_name='Numéro de compte')),
            ],
            options={
                'verbose_name': 'Compte comptable paramétré',
                'verbose_name_plural': 'Comptes comptables paramétrés',
                'ordering': ['cle'],
            },
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro')),
                ('journal', models.CharField(choices=[('VT', 'Ventes'), ('AC', 'Achats'), ('CA', 'Caisse / Trésorerie'), ('OD', 'Opérations diverses')], max_length=2, verbose_name='Journal')),
                ('date', models.DateField(verbose_name='Date comptable')),
                ('piece', models.CharField(max_length=50, verbose_name="Pièce (document d'origine)")),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('objet_id', models.PositiveBigIntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('exportee_le', models.DateTimeField(blank=True, null=True, verbose_name='Exportée vers Sage le')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'verbose_name_plural': 'Écritures comptables',
                'ordering': ['date', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='LigneEcriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte', models.CharField(max_length=20, verbose_name='Compte général')),
                ('compte_tiers', models.CharField(blank=True, max_length=30, verbose_name='Compte tiers')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Débit')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Crédit')),
                ('ecriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite.ecriturecomptable')),
            ],
            options={
                'verbose_name': "Ligne d'écriture",
                'verbose_name_plural': "Lignes d'écriture",
            },
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['content_type', 'objet_id'], name='comptabilit_content_385f90_idx'),
        ),
        migrations.RunPython(comptes_par_defaut, migrations.RunPython.noop),
    ]
