# Generated by Django 6.1 on 2026-09-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0003_ecritures_comptables'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaliedetectee',
            name='cle',
            field=models.CharField(blank=True, db_index=True, help_text="Identifie le cas détecté (ex : impaye-FACT-000012) : pas de doublon tant qu'il est ouvert.", max_length=100, verbose_name='Clé de détection'),
        ),
        migrations.AddField(
            model_name='anomaliedetectee',
            name='commentaire_traitement',
            field=models.TextField(blank=True, verbose_name='Commentaire de traitement'),
        ),
        migrations.AddField(
            model_name='anomaliedetectee',
            name='document_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Identifiant du document'),
        ),
        migrations.AddField(
            model_name='anomaliedetectee',
            name='reference',
            field=models.CharField(blank=True, max_length=50, verbose_name='Référence du document'),
        ),
        migrations.AddField(
            model_name='anomaliedetectee',
            name='type_document',
            field=models.CharField(blank=True, max_length=60, verbose_name='Type de document'),
        ),
        migrations.AlterField(
            model_name='anomaliedetectee',
            name='type_anomalie',
            field=models.CharField(choices=[('ECART_STOCK', 'Écart de stock non justifié'), ('ECART_CAISSE', 'Écart de caisse non justifié'), ('DEPASSEMENT_MATIERE', 'Dépassement de sortie matière'), ('LOT_NON_LIBERE_VENDU', "Tentative de vente d'un lot non libéré"), ('COMMANDE_CLIENT_BLOQUE', 'Commande sur client bloqué'), ('IMPAYE', 'Facture échue impayée'), ('STOCK_SOUS_MINIMUM', 'Stock sous le minimum'), ('LOT_PERIME', 'Lot périmé ou proche de la péremption'), ('SESSION_NON_CLOTUREE', 'Session de caisse non clôturée'), ('DECAISSEMENT_EN_ATTENTE', "Décaissement en attente d'autorisation"), ('AUTRE', 'Autre anomalie')], max_length=30, verbose_name="Type d'anomalie"),
        ),
    ]
