# Generated by Django 6.1 on 2026-09-30 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seuils_par_defaut(apps, schema_editor):
    """Valeurs de départ (5 %, 7 jours, 2 jours), ajustables ensuite par la Comptabilité/DAF."""
    from apps.comptabilite.models import CONTROLES_PAR_DEFAUT
    ParametreControle = apps.get_model("comptabilite", "ParametreControle")
    for cle, (valeur, _minimum, _maximum, _entier) in CONTROLES_PAR_DEFAUT.items():
        ParametreControle.objects.get_or_create(cle=cle, defaults={"valeur": valeur})


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0004_notifications_anomalies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(choices=[('TOLERANCE_DEPASSEMENT_MATIERE', 'Tolérance de dépassement matière (%)'), ('DELAI_ALERTE_PEREMPTION_JOURS', 'Alerte péremption : nombre de jours avant la date'), ('DELAI_DECAISSEMENT_EN_ATTENTE_JOURS', 'Décaissement en attente : alerte après (jours)')], max_length=50, unique=True, verbose_name='Contrôle')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valeur')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Seuil de contrôle automatique',
                'verbose_name_plural': 'Seuils des contrôles automatiques',
                'ordering': ['cle'],
            },
        ),
        migrations.RunPython(seuils_par_defaut, migrations.RunPython.noop),
    ]
