# Generated by Django 6.1 on 2026-10-07 20:21

import apps.core.validation
import django.db.models.deletion
from django.db import migrations, models


def regles_de_depart(apps, schema_editor):
    """
    Q63 : ventes de produits finis en 702, subdivisé par activité (7020 Eau,
    7021 Jus, 7023 Yaourt) ; achats par nature d'article (comptes SYSCOHADA
    usuels, à confirmer par le comptable). Les sous-comptes par format
    s'ajoutent ensuite comme règles plus précises.
    """
    RegleCompte = apps.get_model("comptabilite", "RegleCompte")
    Activite = apps.get_model("industriel", "Activite")
    for code, numero, libelle in (("EAU", "7020", "Ventes produits finis Eau"), ("JUS", "7021", "Ventes produits finis Jus"),
                                  ("YAOURT", "7023", "Ventes produits finis Yaourt")):
        activite = Activite.objects.filter(code=code).first()
        if activite and not RegleCompte.objects.filter(sens="VENTE", activite=activite, article__isnull=True, format__isnull=True).exists():
            RegleCompte.objects.create(sens="VENTE", activite=activite, compte=numero, libelle=libelle)
    for type_article, numero, libelle in (("MATIERE_PREMIERE", "602", "Achats de matières premières"),
                                          ("EMBALLAGE", "608", "Achats d'emballages"),
                                          ("CONSOMMABLE", "604", "Achats de matières et fournitures consommables")):
        if not RegleCompte.objects.filter(sens="ACHAT", type_article=type_article).exists():
            RegleCompte.objects.create(sens="ACHAT", type_article=type_article, compte=numero, libelle=libelle)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notifications_anomalies'),
        ('comptabilite', '0005_seuils_controles'),
        ('industriel', '0002_parametrage_reference'),
        ('referentiel', '0009_article_activite_article_activites_autorisees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportcomptable',
            name='format_fichier',
            field=models.CharField(choices=[('CSV_GENERIQUE', 'CSV générique (UTF-8, dates ISO, point décimal)'), ('XLSX', 'Excel (.xlsx)'), ('JSON', 'JSON'), ('SAGE_CSV', 'CSV Sage 100')], default='SAGE_CSV', max_length=15, verbose_name='Format du fichier'),
        ),
        migrations.CreateModel(
            name='RegleCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens', models.CharField(choices=[('VENTE', 'Ventes (produits finis)'), ('ACHAT', 'Achats (articles approvisionnés)')], max_length=10, verbose_name='Sens')),
                ('compte', models.CharField(max_length=20, verbose_name='Numéro de compte')),
                ('libelle', models.CharField(blank=True, max_length=150, verbose_name='Libellé')),
                ('type_article', models.CharField(blank=True, max_length=30, verbose_name="Catégorie d'article")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='industriel.activite', verbose_name='Activité')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='referentiel.article', verbose_name='Article')),
                ('format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='referentiel.formatarticle', verbose_name='Format')),
                ('unite_vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='referentiel.uniteventearticle', verbose_name='Unité de vente')),
            ],
            options={
                'verbose_name': 'Règle de compte (ventes / achats)',
                'verbose_name_plural': 'Règles de comptes (ventes / achats)',
                'ordering': ['sens', 'compte'],
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
        migrations.RunPython(regles_de_depart, migrations.RunPython.noop),
    ]
