# Generated by Django 6.1 on 2026-08-23 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdreFabrication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro OF')),
                ('quantite_a_produire', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité à produire')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PLANIFIE', 'Planifié'), ('LANCE', 'Lancé'), ('EN_PRODUCTION', 'En production'), ('TERMINE', 'Terminé'), ('CONTROLE_QUALITE', 'Contrôle qualité'), ('LIBERE', 'Libéré'), ('CLOTURE', 'Clôturé')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('date_lancement', models.DateTimeField(blank=True, null=True, verbose_name='Date de lancement')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('agents_affectes', models.ManyToManyField(blank=True, help_text="Agents Production autorisés à intervenir sur cet OF. Un Agent Production ne voit et ne modifie que les OF où il figure ici (règle du cahier des charges : 'accès limité aux OF affectés').", related_name='ordres_fabrication_affectes', to=settings.AUTH_USER_MODEL, verbose_name='Agents Production affectés')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.article', verbose_name='Article à produire')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordres_fabrication_geres', to=settings.AUTH_USER_MODEL, verbose_name='Responsable Production')),
            ],
            options={
                'verbose_name': 'Ordre de fabrication',
                'verbose_name_plural': 'Ordres de fabrication',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='EtapeProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.CharField(choices=[('CAPTAGE', 'Captage'), ('TRAITEMENT', 'Traitement'), ('SOUFFLAGE', 'Soufflage'), ('EMBOUTEILLAGE', 'Embouteillage'), ('ETIQUETAGE', 'Étiquetage'), ('CONDITIONNEMENT', 'Conditionnement')], max_length=20, verbose_name='Étape')),
                ('quantite_produite', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Quantité produite à cette étape')),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name='Début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Agent Production')),
                ('ordre_fabrication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='production.ordrefabrication', verbose_name='Ordre de fabrication')),
            ],
            options={
                'verbose_name': 'Étape de production',
                'verbose_name_plural': 'Étapes de production',
                'ordering': ['ordre_fabrication', 'date_debut'],
            },
        ),
        migrations.CreateModel(
            name='PerteProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_perte', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité perdue')),
                ('motif', models.CharField(choices=[('CASSE', 'Casse'), ('NON_CONFORMITE', 'Non-conformité'), ('PANNE_MACHINE', 'Panne machine'), ('ERREUR_MANIPULATION', 'Erreur de manipulation'), ('AUTRE', 'Autre')], max_length=30, verbose_name='Motif')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date_constat', models.DateTimeField(auto_now_add=True, verbose_name='Date du constat')),
                ('etape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.etapeproduction', verbose_name='Étape concernée')),
                ('ordre_fabrication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pertes', to='production.ordrefabrication', verbose_name='Ordre de fabrication')),
            ],
            options={
                'verbose_name': 'Perte de production',
                'verbose_name_plural': 'Pertes de production',
            },
        ),
        migrations.CreateModel(
            name='PlanProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prevue', models.DateField(verbose_name='Date prévue')),
                ('quantite_prevue', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité prévue')),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=10, verbose_name='Priorité')),
                ('statut', models.CharField(choices=[('PREVU', 'Prévu'), ('EN_COURS', 'En cours'), ('REALISE', 'Réalisé'), ('ANNULE', 'Annulé')], default='PREVU', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.article', verbose_name='Article à produire')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Plan de production',
                'verbose_name_plural': 'Plans de production',
                'ordering': ['date_prevue'],
            },
        ),
        migrations.AddField(
            model_name='ordrefabrication',
            name='plan_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres_fabrication', to='production.planproduction', verbose_name='Plan de production'),
        ),
        migrations.CreateModel(
            name='RetourMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_retournee', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Quantité retournée')),
                ('date_retour', models.DateTimeField(auto_now_add=True, verbose_name='Date de retour')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.article', verbose_name='Matière')),
                ('ordre_fabrication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours_matieres', to='production.ordrefabrication', verbose_name='Ordre de fabrication')),
            ],
            options={
                'verbose_name': 'Retour matière',
                'verbose_name_plural': 'Retours matières',
            },
        ),
        migrations.CreateModel(
            name='SortieMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_sortie', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Quantité sortie')),
                ('type_sortie', models.CharField(choices=[('NORMALE', 'Normale'), ('COMPLEMENTAIRE', 'Complémentaire (dépassement)')], default='NORMALE', max_length=20, verbose_name='Type de sortie')),
                ('motif', models.TextField(blank=True, help_text='Obligatoire si la sortie est de type Complémentaire.', verbose_name='Motif')),
                ('date_sortie', models.DateTimeField(auto_now_add=True, verbose_name='Date de sortie')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.article', verbose_name='Matière')),
                ('ordre_fabrication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sorties_matieres', to='production.ordrefabrication', verbose_name='Ordre de fabrication')),
                ('valide_par', models.ForeignKey(blank=True, help_text='Rempli uniquement pour les sorties complémentaires (validation du Responsable Production, §8.7).', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Sortie matière',
                'verbose_name_plural': 'Sorties matières',
                'ordering': ['-date_sortie'],
            },
        ),
        migrations.CreateModel(
            name='BesoinMatierePrevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_theorique', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Quantité théorique nécessaire')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.article', verbose_name='Matière')),
                ('ordre_fabrication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='besoins_matieres', to='production.ordrefabrication', verbose_name='Ordre de fabrication')),
            ],
            options={
                'verbose_name': 'Besoin matière prévu',
                'verbose_name_plural': 'Besoins matières prévus',
                'unique_together': {('ordre_fabrication', 'matiere')},
            },
        ),
    ]
