# Generated by Django 6.1.1 on 2026-09-16 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Correspondance entre l'ancien workflow de statuts (avant le cahier
# des charges mis à jour) et le nouveau (§5.4.2). Nécessaire car les
# OF déjà créés sur une base existante portent des valeurs de statut
# qui n'existent plus dans les nouveaux choix - sans cette conversion,
# ils resteraient bloqués sur une valeur "orpheline" (toujours stockée
# telle quelle en base, mais non reconnue par les nouveaux choix, donc
# affichée sans libellé côté API/admin).
CORRESPONDANCE_ANCIENS_STATUTS = {
    "PLANIFIE": "A_PREPARER",
    "LANCE": "MATIERES_EN_PREPARATION",
    "TERMINE": "PRODUCTION_TERMINEE",
    "CONTROLE_QUALITE": "EN_CONTROLE",
    "LIBERE": "PRODUCTION_TERMINEE",
    # BROUILLON, EN_PRODUCTION et CLOTURE existent à l'identique dans
    # les deux systèmes : aucune conversion nécessaire pour ceux-là.
}


def convertir_anciens_statuts_of(apps, schema_editor):
    OrdreFabrication = apps.get_model("production", "OrdreFabrication")
    for ancien, nouveau in CORRESPONDANCE_ANCIENS_STATUTS.items():
        OrdreFabrication.objects.filter(statut=ancien).update(statut=nouveau)


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('referentiel', '0002_article_activite_analytique_article_centre_cout_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordrefabrication',
            name='date_lancement',
        ),
        migrations.AddField(
            model_name='ordrefabrication',
            name='date_debut_production',
            field=models.DateTimeField(blank=True, help_text="Renseignée automatiquement au passage à 'En production'.", null=True, verbose_name='Date de début de production'),
        ),
        migrations.AddField(
            model_name='ordrefabrication',
            name='equipe',
            field=models.CharField(blank=True, max_length=100, verbose_name='Équipe'),
        ),
        migrations.AddField(
            model_name='ordrefabrication',
            name='motif_annulation',
            field=models.TextField(blank=True, help_text="Renseigné uniquement si l'OF est annulé (§5.4.2).", verbose_name="Motif d'annulation"),
        ),
        migrations.AddField(
            model_name='perteproduction',
            name='taux_perte',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peut être calculé côté client (quantité perdue / quantité entrée) ou saisi directement.', max_digits=5, null=True, verbose_name='Taux de perte (%)'),
        ),
        migrations.AddField(
            model_name='planproduction',
            name='commentaire',
            field=models.TextField(blank=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='retourmatiere',
            name='motif',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motif'),
        ),
        migrations.AlterField(
            model_name='ordrefabrication',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture'),
        ),
        migrations.AlterField(
            model_name='ordrefabrication',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('A_PREPARER', 'À préparer'), ('MATIERES_EN_PREPARATION', 'Matières en préparation'), ('PRET', 'Prêt'), ('EN_PRODUCTION', 'En production'), ('PRODUCTION_TERMINEE', 'Production terminée'), ('EN_CONTROLE', 'En contrôle'), ('CLOTURE', 'Clôturé'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=30, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='perteproduction',
            name='motif',
            field=models.CharField(choices=[('CASSE', 'Casse'), ('MAUVAIS_REGLAGE', 'Mauvais réglage'), ('FUITE', 'Fuite'), ('DEFAUT_MATIERE', 'Défaut matière'), ('DEFAUT_BOUTEILLE', 'Défaut bouteille'), ('CONTROLE_QUALITE', 'Contrôle qualité'), ('ARRET_MACHINE', 'Arrêt machine'), ('NETTOYAGE', 'Nettoyage'), ('ERREUR_OPERATEUR', 'Erreur opérateur'), ('AUTRE', 'Autre')], max_length=30, verbose_name='Motif'),
        ),
        migrations.AlterField(
            model_name='planproduction',
            name='statut',
            field=models.CharField(choices=[('PREVISION', 'Prévision'), ('A_CONVERTIR_EN_OF', 'À convertir en OF'), ('CONVERTIE', 'Convertie en OF'), ('ANNULEE', 'Annulée')], default='PREVISION', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='sortiematiere',
            name='valide_par',
            field=models.ForeignKey(blank=True, help_text='Rempli uniquement pour les sorties complémentaires.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.CreateModel(
            name='DemandeComplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='N° complément')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantité')),
                ('motif', models.TextField(help_text="Obligatoire (ex : 'Défauts au soufflage').", verbose_name='Motif')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVEE_ET_LIVREE', 'Approuvée et livrée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=25, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.article', verbose_name='Matière')),
                ('ordre_fabrication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_complementaires', to='production.ordrefabrication', verbose_name='Ordre de fabrication')),
            ],
            options={
                'verbose_name': 'Demande complémentaire',
                'verbose_name_plural': 'Demandes complémentaires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DemandeMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='N° demande')),
                ('quantite_demandee', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantité demandée')),
                ('statut', models.CharField(choices=[('A_PREPARER', 'À préparer'), ('PARTIELLEMENT_PREPAREE', 'Partiellement préparée'), ('PREPAREE', 'Préparée'), ('LIVREE_A_LA_PRODUCTION', 'Livrée à la production'), ('ANNULEE', 'Annulée')], default='A_PREPARER', max_length=25, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.article', verbose_name='Matière')),
                ('ordre_fabrication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_matieres', to='production.ordrefabrication', verbose_name='Ordre de fabrication')),
            ],
            options={
                'verbose_name': 'Demande de matière',
                'verbose_name_plural': 'Demandes de matières',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SuiviEau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_capte_l', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Volume capté (L)')),
                ('volume_envoye_traitement_l', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Volume envoyé au traitement (L)')),
                ('volume_obtenu_traitement_l', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Volume obtenu après traitement (L)')),
                ('volume_envoye_embouteillage_l', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Volume envoyé à l'embouteillage (L)")),
                ('bouteilles_produites', models.PositiveIntegerField(verbose_name='Bouteilles produites')),
                ('bouteilles_conformes', models.PositiveIntegerField(verbose_name='Bouteilles conformes')),
                ('bouteilles_rejetees', models.PositiveIntegerField(default=0, verbose_name='Bouteilles rejetées')),
                ('nombre_packs', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de packs')),
                ('ordre_fabrication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suivi_eau', to='production.ordrefabrication', verbose_name='Ordre de fabrication')),
            ],
            options={
                'verbose_name': "Suivi de l'eau",
                'verbose_name_plural': "Suivis de l'eau",
            },
        ),
        migrations.CreateModel(
            name='SuiviProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('equipe', models.CharField(blank=True, max_length=100, verbose_name='Équipe')),
                ('quantite_entree', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité entrée')),
                ('quantite_produite', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Quantité produite')),
                ('quantite_conforme', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Quantité conforme')),
                ('quantite_rejetee', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Quantité rejetée')),
                ('arrets', models.TextField(blank=True, help_text="Ex : 'Arrêt 15 min réglage'", verbose_name='Arrêts')),
                ('incidents', models.TextField(blank=True, verbose_name='Incidents')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('ordre_fabrication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_production', to='production.ordrefabrication', verbose_name='Ordre de fabrication')),
            ],
            options={
                'verbose_name': 'Suivi de production',
                'verbose_name_plural': 'Suivis de production',
                'ordering': ['-date', '-heure_debut'],
            },
        ),
        migrations.RunPython(convertir_anciens_statuts_of, migrations.RunPython.noop),
    ]