# Generated by Django 6.1 on 2026-09-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_remove_ordrefabrication_date_lancement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandematiere',
            name='quantite_livree',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Cumul des livraisons (partielles) du magasin : empêche de livrer plus que demandé.', max_digits=14, verbose_name='Quantité déjà livrée'),
        ),
    ]
