# Generated by Django 6.1 on 2026-09-30 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_demandematiere_quantite_livree'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perteproduction',
            name='saisi_par',
            field=models.ForeignKey(blank=True, help_text="Traçabilité : renseigné automatiquement avec l'utilisateur connecté.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pertes_saisies', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par'),
        ),
        migrations.AddField(
            model_name='suivieau',
            name='saisi_par',
            field=models.ForeignKey(blank=True, help_text="Traçabilité : renseigné automatiquement avec l'utilisateur connecté.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suivis_eau_saisis', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par'),
        ),
        migrations.AddField(
            model_name='suiviproduction',
            name='saisi_par',
            field=models.ForeignKey(blank=True, help_text="Traçabilité : renseigné automatiquement avec l'utilisateur connecté.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suivis_production_saisis', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par'),
        ),
    ]
