# Generated by Django 6.1 on 2026-10-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_agent_production_tracabilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='besoinmatiereprevu',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Montant'),
        ),
        migrations.AddField(
            model_name='besoinmatiereprevu',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Prix de la fiche technique au moment de la création de l'OF (figé).", max_digits=14, verbose_name='Prix unitaire'),
        ),
        migrations.AddField(
            model_name='demandematiere',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Montant'),
        ),
        migrations.AddField(
            model_name='demandematiere',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Repris du besoin chiffré de l'OF.", max_digits=14, verbose_name='Prix unitaire'),
        ),
    ]
