# Generated by Django 6.1 on 2026-10-06 21:39

import apps.core.validation
import apps.production.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industriel', '0001_initial'),
        ('production', '0005_chiffrage_matieres'),
        ('referentiel', '0009_article_activite_article_activites_autorisees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangementSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(verbose_name='Début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('duree_arret_min', models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name="Temps d'arrêt (min)")),
                ('duree_nettoyage_min', models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Nettoyage (min)')),
                ('duree_reglage_min', models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Réglage (min)')),
                ('quantite_essais', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Quantité consommée en essais')),
                ('rebuts_demarrage', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Rebuts de démarrage')),
                ('cout_nettoyage', models.DecimalField(blank=True, decimal_places=2, help_text='Produits de nettoyage, intervention... si connu.', max_digits=14, null=True, verbose_name='Coût réel du nettoyage')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
            ],
            options={
                'verbose_name': 'Changement de série',
                'verbose_name_plural': 'Changements de série',
                'ordering': ['-date_debut'],
            },
            bases=(apps.production.models.SaisieSurOFMixin, apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
        migrations.CreateModel(
            name='ConsommationLotMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Quantité consommée')),
                ('quantite_retournee', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Quantité retournée')),
            ],
            options={
                'verbose_name': 'Consommation de lot matière',
                'verbose_name_plural': 'Consommations de lots matières',
            },
        ),
        migrations.CreateModel(
            name='ParametreProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloquer_lancement_stock_insuffisant', models.BooleanField(default=True, help_text='Décoché : le lancement est seulement signalé (avertissement).', verbose_name="Bloquer le lancement d'un OF si le stock est insuffisant")),
                ('controle_qualite_bloque_cloture', models.BooleanField(default=True, verbose_name='Bloquer la clôture si des contrôles bloquants manquent ou sont non conformes')),
            ],
            options={
                'verbose_name': 'Paramètres de production',
                'verbose_name_plural': 'Paramètres de production',
            },
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='duree_arret_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Arrêts (minutes)'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='energie_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Énergie consommée (kWh)'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='energie_mesuree',
            field=models.BooleanField(default=False, help_text='Décoché = valeur estimée (jamais présentée comme une mesure).', verbose_name='kWh relevés sur un compteur'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='equipement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='industriel.equipement', verbose_name='Machine'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='heures_machine',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Compteur d'heures ; vide = durée début -> fin moins les arrêts.", max_digits=8, null=True, verbose_name='Heures machine'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='industriel.poste', verbose_name='Poste'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='quantite_entree',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Quantité entrée'),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='quantite_rejetee',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Quantité rejetée'),
        ),
        migrations.AddField(
            model_name='ordrefabrication',
            name='circuit',
            field=models.ForeignKey(blank=True, help_text='Associé automatiquement (circuit validé le plus précis).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordres_fabrication', to='industriel.circuit', verbose_name='Circuit'),
        ),
        migrations.AddField(
            model_name='ordrefabrication',
            name='date_prevue',
            field=models.DateField(blank=True, null=True, verbose_name='Date prévue'),
        ),
        migrations.AddField(
            model_name='ordrefabrication',
            name='fiche_technique',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordres_fabrication', to='referentiel.fichetechnique', verbose_name='Recette appliquée'),
        ),
        migrations.AddField(
            model_name='ordrefabrication',
            name='ligne',
            field=models.ForeignKey(blank=True, help_text="Ligne compatible avec le format. Détermine l'usine (magasin matières et stock produits finis).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordres_fabrication', to='industriel.ligne', verbose_name='Ligne'),
        ),
        migrations.AddField(
            model_name='perteproduction',
            name='etape_code',
            field=models.CharField(blank=True, help_text='Ex : SOUFFLAGE, REMPLISSAGE.', max_length=30, verbose_name='Étape (code)'),
        ),
        migrations.AddField(
            model_name='perteproduction',
            name='matiere',
            field=models.ForeignKey(blank=True, help_text='Permet de valoriser la perte au coût moyen (CMUP).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pertes', to='referentiel.article', verbose_name='Matière / emballage perdu'),
        ),
        migrations.AddField(
            model_name='perteproduction',
            name='nature',
            field=models.CharField(choices=[('PREFORMES_REJETEES', 'Préformes rejetées (soufflage)'), ('SUR_REMPLISSAGE', 'Sur-remplissage'), ('REBUT_REMPLISSAGE', 'Rebuts de remplissage'), ('ETIQUETTES', 'Étiquettes perdues'), ('FILM', 'Film perdu (plastification)'), ('PACKS_NON_CONFORMES', 'Packs non conformes'), ('CONCENTRE_REJETE', 'Concentré rejeté (osmose)'), ('EAU', "Perte d'eau"), ('PRODUIT_DEMARRAGE', 'Produits / rebuts de démarrage (changement de série)'), ('CASSE_STOCKAGE', 'Casse en stockage'), ('AUTRE', 'Autre')], default='AUTRE', max_length=30, verbose_name='Nature de la perte'),
        ),
        migrations.AddField(
            model_name='perteproduction',
            name='valeur',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=16, null=True, verbose_name='Valeur de la perte'),
        ),
    ]
