# Generated by Django 6.1 on 2026-10-06 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industriel', '0001_initial'),
        ('production', '0006_changementserie_consommationlotmatiere_and_more'),
        ('referentiel', '0009_article_activite_article_activites_autorisees_and_more'),
        ('stocks', '0004_depot_activite_depot_articles_autorises_depot_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sortiematiere',
            name='lot_matiere',
            field=models.ForeignKey(blank=True, help_text="Vide = lots consommés automatiquement, les plus anciens (DLC) d'abord.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stocks.lotmatiere', verbose_name='Lot imposé'),
        ),
        migrations.AlterField(
            model_name='etapeproduction',
            name='etape',
            field=models.CharField(help_text="Code d'une étape du paramétrage (CAPTAGE, PREPARATION, REMPLISSAGE...) ; si l'OF a un circuit, une étape de ce circuit.", max_length=30, verbose_name='Étape'),
        ),
        migrations.AddField(
            model_name='changementserie',
            name='article_precedent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='referentiel.article', verbose_name='Produit / format précédent'),
        ),
        migrations.AddField(
            model_name='changementserie',
            name='ligne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='industriel.ligne', verbose_name='Ligne'),
        ),
        migrations.AddField(
            model_name='changementserie',
            name='ordre_fabrication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changements_serie', to='production.ordrefabrication', verbose_name='OF démarré après le changement'),
        ),
        migrations.AddField(
            model_name='changementserie',
            name='saisi_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par'),
        ),
        migrations.AddField(
            model_name='consommationlotmatiere',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consommations', to='stocks.lotmatiere', verbose_name='Lot matière'),
        ),
        migrations.AddField(
            model_name='consommationlotmatiere',
            name='sortie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consommations_lots', to='production.sortiematiere', verbose_name='Sortie matière'),
        ),
    ]
