# Generated by Django 6.1 on 2026-10-07 12:30

import apps.core.validation
import apps.production.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industriel', '0002_parametrage_reference'),
        ('production', '0007_sortiematiere_lot_matiere_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('CUVE', 'Cuve préparée'), ('NETTOYAGE', 'Nettoyage / désinfection'), ('ARRET_REDEMARRAGE', 'Arrêt puis redémarrage')], max_length=20, verbose_name='Événement')),
                ('numero_cuve', models.CharField(blank=True, max_length=40, verbose_name='N° de cuvée / batch')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Volume (L)')),
                ('duree_min', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Durée (min)')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='industriel.equipement', verbose_name='Cuve / machine')),
                ('ordre_fabrication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evenements', to='production.ordrefabrication', verbose_name='OF')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
            ],
            options={
                'verbose_name': 'Événement de production',
                'verbose_name_plural': 'Événements de production',
                'ordering': ['-date'],
            },
            bases=(apps.production.models.SaisieSurOFMixin, apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
    ]
