# Generated by Django 6.1 on 2026-10-07 20:09

import apps.core.validation
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industriel', '0002_parametrage_reference'),
        ('production', '0008_tracabilite_palettes_declencheurs'),
        ('referentiel', '0009_article_activite_article_activites_autorisees_and_more'),
        ('stocks', '0005_tracabilite_palettes_declencheurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordrefabrication',
            name='date_debut_prevue',
            field=models.DateTimeField(blank=True, help_text='Planning par ligne : deux OF ne se chevauchent pas sur une même ligne.', null=True, verbose_name='Début planifié'),
        ),
        migrations.AddField(
            model_name='ordrefabrication',
            name='date_fin_prevue',
            field=models.DateTimeField(blank=True, help_text="Calculée depuis la cadence de la ligne si elle est connue et que la fin n'est pas saisie.", null=True, verbose_name='Fin planifiée'),
        ),
        migrations.AddField(
            model_name='parametreproduction',
            name='heures_ouvrees_par_jour',
            field=models.DecimalField(decimal_places=1, default=8, help_text="Capacité journalière d'une ligne pour le planning (ex : 8, 16 en 2 équipes, 24).", max_digits=4, verbose_name='Heures de production par jour et par ligne'),
        ),
        migrations.AddField(
            model_name='planproduction',
            name='ligne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='industriel.ligne', verbose_name='Ligne prévue'),
        ),
        migrations.CreateModel(
            name='FormatOF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_a_produire', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité à produire')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='referentiel.article', verbose_name='Format')),
                ('ordre_fabrication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats_supplementaires', to='production.ordrefabrication', verbose_name='OF')),
            ],
            options={
                'verbose_name': "Format supplémentaire d'OF",
                'verbose_name_plural': "Formats supplémentaires d'OF",
                'unique_together': {('ordre_fabrication', 'article')},
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
        migrations.CreateModel(
            name='ReservationMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_reservee', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Quantité réservée')),
                ('quantite_restante', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Reste réservé')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Réservé le')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stocks.depot', verbose_name='Magasin')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='referentiel.article', verbose_name='Matière')),
                ('ordre_fabrication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='production.ordrefabrication', verbose_name='OF')),
            ],
            options={
                'verbose_name': 'Réservation de matière',
                'verbose_name_plural': 'Réservations de matières',
                'unique_together': {('ordre_fabrication', 'matiere', 'depot')},
            },
        ),
    ]
