# Generated by Django 6.1 on 2026-10-07 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industriel', '0003_ajustements_questionnaire'),
        ('production', '0009_of_multiformat_reservation_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='perteproduction',
            name='type_quantite',
            field=models.CharField(choices=[('REELLE', 'Réelle (comptée)'), ('ESTIMEE', 'Estimée')], default='REELLE', help_text='Q34 : distinguer les pertes réellement comptées des pertes estimées.', max_length=10, verbose_name='Quantité'),
        ),
        migrations.CreateModel(
            name='DonneeObligatoireEtape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ', models.CharField(choices=[('quantite_entree', 'Quantité entrée'), ('quantite_produite', 'Quantité produite'), ('quantite_rejetee', 'Quantité rejetée'), ('date_debut', 'Heure de début'), ('date_fin', 'Heure de fin'), ('duree_arret_min', 'Arrêts (minutes)'), ('heures_machine', 'Heures machine'), ('energie_kwh', 'Énergie (kWh)'), ('poste', 'Poste'), ('equipement', 'Machine')], max_length=30, verbose_name='Donnée')),
                ('obligatoire', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donnees_saisie', to='industriel.etapestandard', verbose_name='Étape')),
            ],
            options={
                'verbose_name': 'Donnée à saisir par étape',
                'verbose_name_plural': 'Données à saisir par étape',
                'ordering': ['etape__ordre_reference', 'champ'],
                'unique_together': {('etape', 'champ')},
            },
        ),
    ]
