# Generated by Django 6.1.1 on 2026-09-16 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportGenere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('JOURNALIER', 'Journalier'), ('MENSUEL', 'Mensuel')], max_length=15, verbose_name='Période')),
                ('date_rapport', models.DateField(verbose_name='Date du rapport')),
                ('contenu', models.JSONField(help_text='Copie figée de la réponse du tableau de bord Direction à cette date.', verbose_name='Contenu du rapport')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('genere_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
            ],
            options={
                'verbose_name': 'Rapport généré',
                'verbose_name_plural': 'Rapports générés',
                'ordering': ['-date_rapport'],
                'unique_together': {('periode', 'date_rapport')},
            },
        ),
    ]