# Generated by Django 6.1 on 2026-08-23 21:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('profil', models.CharField(choices=[('RESPONSABLE_PRODUCTION', 'Responsable Production'), ('AGENT_PRODUCTION', 'Agent Production'), ('MAGASINIER', 'Magasinier'), ('RESPONSABLE_QUALITE', 'Responsable Qualité'), ('RESPONSABLE_ACHATS', 'Responsable Achat'), ('COMMERCIAL', 'Commercial'), ('CAISSIER', 'Caissier'), ('RESPONSABLE_DISTRIBUTION', 'Responsable Distribution'), ('CHAUFFEUR', 'Chauffeur / Livreur'), ('COMPTABILITE_DAF', 'Comptabilité / DAF'), ('DIRECTION', 'PDG / Direction'), ('ADMIN_SI', 'Administrateur SI')], help_text="Rôle métier de l'utilisateur dans l'application. Détermine ses droits d'accès par défaut.", max_length=32, verbose_name='Profil')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('actif', models.BooleanField(default=True, help_text="Un compte désactivé ne peut plus se connecter, sans supprimer son historique d'actions.", verbose_name='Compte actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='JournalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('ACCUEIL', 'Accueil / Tableau de bord'), ('REFERENTIEL', 'Référentiel'), ('ACHATS', 'Achats'), ('STOCKS', 'Stocks'), ('PRODUCTION', 'Production'), ('QUALITE', 'Qualité / Traçabilité'), ('COMMERCIAL', 'Gestion commerciale'), ('CAISSE', 'Caisse'), ('DISTRIBUTION', 'Distribution / Logistique'), ('COUTS', 'Coûts & Rentabilité'), ('COMPTABILITE', 'Pilotage / Comptabilité'), ('ADMINISTRATION', 'Administration / Droits')], max_length=32, verbose_name='Module')),
                ('action', models.CharField(help_text="Ex : 'création OF', 'libération lot', 'annulation commande'", max_length=100, verbose_name='Action')),
                ('document_type', models.CharField(blank=True, max_length=100, verbose_name='Type de document')),
                ('document_id', models.CharField(blank=True, max_length=100, verbose_name='Référence du document')),
                ('ancienne_valeur', models.TextField(blank=True, verbose_name='Ancienne valeur')),
                ('nouvelle_valeur', models.TextField(blank=True, verbose_name='Nouvelle valeur')),
                ('motif', models.TextField(blank=True, verbose_name='Motif')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Action journalisée',
                'verbose_name_plural': 'Journal des actions',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='MatriceDroit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil', models.CharField(choices=[('RESPONSABLE_PRODUCTION', 'Responsable Production'), ('AGENT_PRODUCTION', 'Agent Production'), ('MAGASINIER', 'Magasinier'), ('RESPONSABLE_QUALITE', 'Responsable Qualité'), ('RESPONSABLE_ACHATS', 'Responsable Achat'), ('COMMERCIAL', 'Commercial'), ('CAISSIER', 'Caissier'), ('RESPONSABLE_DISTRIBUTION', 'Responsable Distribution'), ('CHAUFFEUR', 'Chauffeur / Livreur'), ('COMPTABILITE_DAF', 'Comptabilité / DAF'), ('DIRECTION', 'PDG / Direction'), ('ADMIN_SI', 'Administrateur SI')], max_length=32, verbose_name='Profil')),
                ('module', models.CharField(choices=[('ACCUEIL', 'Accueil / Tableau de bord'), ('REFERENTIEL', 'Référentiel'), ('ACHATS', 'Achats'), ('STOCKS', 'Stocks'), ('PRODUCTION', 'Production'), ('QUALITE', 'Qualité / Traçabilité'), ('COMMERCIAL', 'Gestion commerciale'), ('CAISSE', 'Caisse'), ('DISTRIBUTION', 'Distribution / Logistique'), ('COUTS', 'Coûts & Rentabilité'), ('COMPTABILITE', 'Pilotage / Comptabilité'), ('ADMINISTRATION', 'Administration / Droits')], max_length=32, verbose_name='Module')),
                ('peut_consulter', models.BooleanField(default=False, verbose_name='Peut consulter')),
                ('peut_creer', models.BooleanField(default=False, verbose_name='Peut créer')),
                ('peut_modifier', models.BooleanField(default=False, verbose_name='Peut modifier')),
                ('peut_valider', models.BooleanField(default=False, verbose_name='Peut valider')),
                ('peut_annuler', models.BooleanField(default=False, verbose_name='Peut annuler')),
                ('peut_exporter', models.BooleanField(default=False, verbose_name='Peut exporter')),
                ('peut_parametrer', models.BooleanField(default=False, verbose_name='Peut paramétrer')),
            ],
            options={
                'verbose_name': "Droit d'accès",
                'verbose_name_plural': "Matrice des droits d'accès",
                'ordering': ['profil', 'module'],
                'unique_together': {('profil', 'module')},
            },
        ),
    ]
