# Generated by Django 6.1 on 2026-09-14 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='actif',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_desactivation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de désactivation'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='desactive_par',
            field=models.ForeignKey(blank=True, help_text='Traçabilité : qui a désactivé ce compte, le cas échéant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_desactives', to=settings.AUTH_USER_MODEL, verbose_name='Désactivé par'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='profil',
            field=models.CharField(choices=[('RESPONSABLE_PRODUCTION', 'Responsable Production'), ('AGENT_PRODUCTION', 'Agent Production'), ('MAGASINIER', 'Magasinier'), ('RESPONSABLE_QUALITE', 'Responsable Qualité'), ('RESPONSABLE_ACHATS', 'Responsable Achat'), ('COMMERCIAL', 'Commercial'), ('CAISSIER', 'Caissier'), ('RESPONSABLE_DISTRIBUTION', 'Responsable Distribution'), ('CHAUFFEUR', 'Chauffeur / Livreur'), ('COMPTABILITE_DAF', 'Comptabilité / DAF'), ('DIRECTION', 'PDG / Direction'), ('ADMIN_SI', 'Administrateur SI')], help_text="Rôle métier de l'utilisateur dans l'application. Détermine ses droits d'accès via la matrice de droits.", max_length=32, verbose_name='Profil'),
        ),
    ]
