# Generated by Django 6.1.1 on 2026-09-14 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='actif',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_desactivation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de désactivation'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='desactive_par',
            field=models.ForeignKey(blank=True, help_text='Traçabilité : qui a désactivé ce compte, le cas échéant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_desactives', to=settings.AUTH_USER_MODEL, verbose_name='Désactivé par'),
        ),
    ]