# Generated by Django 6.1 on 2026-09-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_remove_utilisateur_actif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='profil',
            field=models.CharField(choices=[('RESPONSABLE_PRODUCTION', 'Responsable Production'), ('AGENT_PRODUCTION', 'Agent Production'), ('MAGASINIER', 'Magasinier'), ('RESPONSABLE_QUALITE', 'Responsable Qualité'), ('RESPONSABLE_ACHATS', 'Responsable Achat'), ('COMMERCIAL', 'Commercial'), ('CAISSIER', 'Caissier'), ('RESPONSABLE_DISTRIBUTION', 'Responsable Distribution'), ('CHAUFFEUR', 'Chauffeur / Livreur'), ('COMPTABILITE_DAF', 'Comptabilité / DAF'), ('DIRECTION', 'PDG / Direction'), ('ADMIN_SI', 'Administrateur SI')], help_text="Rôle métier de l'utilisateur dans l'application. Détermine ses droits d'accès via la matrice de droits.", max_length=32, verbose_name='Profil'),
        ),
    ]
