# Generated by Django 6.1 on 2026-09-15 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_alter_utilisateur_profil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatriceDroit',
        ),
    ]
