# Generated by Django 6.1 on 2026-09-30 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_delete_matricedroit'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalaction',
            name='adresse_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AddField(
            model_name='journalaction',
            name='requete',
            field=models.CharField(blank=True, help_text='Ex : POST /api/caisse/decaissements/12/autoriser/', max_length=255, verbose_name='Requête'),
        ),
        migrations.AlterField(
            model_name='journalaction',
            name='utilisateur',
            field=models.ForeignKey(blank=True, help_text='Vide pour une action du système (commande planifiée, migration...).', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
