# Generated by Django 6.1 on 2026-08-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la caisse')),
                ('emplacement', models.CharField(blank=True, max_length=150, verbose_name='Emplacement')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Caisse',
                'verbose_name_plural': 'Caisses',
            },
        ),
        migrations.CreateModel(
            name='EcartCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_ecart', models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Montant de l'écart")),
                ('justification', models.TextField(verbose_name='Justification')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': "Justification d'écart de caisse",
                'verbose_name_plural': "Justifications d'écarts de caisse",
            },
        ),
        migrations.CreateModel(
            name='Encaissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant encaissé')),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque')], max_length=15, verbose_name='Mode de paiement')),
                ('date_encaissement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'encaissement")),
            ],
            options={
                'verbose_name': 'Encaissement',
                'verbose_name_plural': 'Encaissements',
                'ordering': ['-date_encaissement'],
            },
        ),
        migrations.CreateModel(
            name='SessionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_ouverture', models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Solde d'ouverture")),
                ('solde_theorique_cloture', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Solde théorique à la clôture')),
                ('solde_compte_cloture', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Solde compté à la clôture')),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('CLOTUREE', 'Clôturée')], default='OUVERTE', max_length=15, verbose_name='Statut')),
                ('date_ouverture', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ouverture")),
                ('date_cloture', models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture')),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'ordering': ['-date_ouverture'],
            },
        ),
    ]
