# Generated by Django 6.1 on 2026-08-23 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caisse', '0001_initial'),
        ('commercial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ecartcaisse',
            name='valide_par',
            field=models.ForeignKey(blank=True, help_text='Rempli par la Comptabilité/DAF après contrôle.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='encaissement',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encaissements', to='commercial.facture', verbose_name='Facture'),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caisse.caisse', verbose_name='Caisse'),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='caissier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Caissier'),
        ),
        migrations.AddField(
            model_name='encaissement',
            name='session_caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encaissements', to='caisse.sessioncaisse', verbose_name='Session de caisse'),
        ),
        migrations.AddField(
            model_name='ecartcaisse',
            name='session_caisse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justification_ecart', to='caisse.sessioncaisse', verbose_name='Session de caisse'),
        ),
    ]
