# Generated by Django 6.1.1 on 2026-09-16 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decaissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('motif', models.TextField(verbose_name='Motif')),
                ('beneficiaire', models.CharField(blank=True, max_length=200, verbose_name='Bénéficiaire')),
                ('date_decaissement', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('autorise_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decaissements_autorises', to=settings.AUTH_USER_MODEL, verbose_name='Autorisé par')),
                ('effectue_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decaissements_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par (caissier)')),
                ('session_caisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decaissements', to='caisse.sessioncaisse', verbose_name='Session de caisse')),
            ],
            options={
                'verbose_name': 'Décaissement',
                'verbose_name_plural': 'Décaissements',
                'ordering': ['-date_decaissement'],
            },
        ),
    ]