# Generated by Django 6.1 on 2026-09-29 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0004_caisse_par_defaut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caisse',
            name='caissier',
            field=models.OneToOneField(blank=True, help_text='Le caissier qui ouvre et clôture ses sessions sur cette caisse (un caissier = une caisse).', limit_choices_to={'profil': 'CAISSIER'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caisse_affectee', to=settings.AUTH_USER_MODEL, verbose_name='Caissier affecté'),
        ),
        migrations.AddField(
            model_name='caisse',
            name='est_principale',
            field=models.BooleanField(default=False, editable=False, help_text='Caisse de consolidation créée par le système (une seule).', verbose_name='Caisse principale'),
        ),
        migrations.AddField(
            model_name='encaissement',
            name='encaisse_par',
            field=models.ForeignKey(blank=True, help_text='Traçabilité : le caissier qui a encaissé (renseigné automatiquement).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encaissements_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Encaissé par'),
        ),
        migrations.AlterField(
            model_name='sessioncaisse',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='caisse.caisse', verbose_name='Caisse'),
        ),
        migrations.AlterField(
            model_name='sessioncaisse',
            name='solde_ouverture',
            field=models.DecimalField(decimal_places=2, help_text='Automatique : 0 à la première ouverture de la caisse, puis le solde COMPTÉ de la clôture précédente (l\'argent réellement en caisse).', max_digits=14, verbose_name="Solde d'ouverture"),
        ),
        migrations.AddConstraint(
            model_name='caisse',
            constraint=models.UniqueConstraint(condition=models.Q(('est_principale', True)), fields=('est_principale',), name='une_seule_caisse_principale'),
        ),
    ]
