# Generated by Django 6.1 on 2026-09-29 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0006_caisse_principale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='decaissement',
            name='autorise_par',
            field=models.ForeignKey(help_text='Direction ou Comptabilité/DAF uniquement.', limit_choices_to={'is_active': True, 'profil__in': ('DIRECTION', 'COMPTABILITE_DAF')}, on_delete=django.db.models.deletion.PROTECT, related_name='decaissements_autorises', to=settings.AUTH_USER_MODEL, verbose_name='Autorisé par'),
        ),
    ]
