# Generated by Django 6.1 on 2026-09-30 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def decaissements_existants_effectues(apps, schema_editor):
    """Les décaissements antérieurs au circuit d'autorisation ont réellement fait sortir l'argent."""
    Decaissement = apps.get_model("caisse", "Decaissement")
    for decaissement in Decaissement.objects.all():
        decaissement.statut = "EFFECTUE"
        decaissement.date_autorisation = decaissement.date_decaissement
        decaissement.date_execution = decaissement.date_decaissement
        decaissement.save(update_fields=["statut", "date_autorisation", "date_execution"])


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0007_autorisation_decaissement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='decaissement',
            name='date_autorisation',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'autorisation / de refus"),
        ),
        migrations.AddField(
            model_name='decaissement',
            name='date_execution',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de sortie d'argent"),
        ),
        migrations.AddField(
            model_name='decaissement',
            name='motif_refus',
            field=models.TextField(blank=True, verbose_name='Motif du refus'),
        ),
        migrations.AddField(
            model_name='decaissement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', "En attente d'autorisation"), ('AUTORISE', 'Autorisé'), ('REFUSE', 'Refusé'), ('EFFECTUE', 'Effectué')], default='EN_ATTENTE', max_length=15, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='decaissement',
            name='autorise_par',
            field=models.ForeignKey(blank=True, help_text="Direction ou Comptabilité/DAF : renseigné par l'action Autoriser / Refuser.", limit_choices_to={'is_active': True, 'profil__in': ('DIRECTION', 'COMPTABILITE_DAF')}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decaissements_autorises', to=settings.AUTH_USER_MODEL, verbose_name='Autorisé / refusé par'),
        ),
        migrations.AlterField(
            model_name='decaissement',
            name='date_decaissement',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande'),
        ),
        migrations.AlterField(
            model_name='decaissement',
            name='effectue_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decaissements_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Caissier'),
        ),
        migrations.RunPython(decaissements_existants_effectues, migrations.RunPython.noop),
    ]
