# Generated by Django 6.1 on 2026-08-23 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code article')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('type_article', models.CharField(choices=[('MATIERE_PREMIERE', 'Matière première'), ('PRODUIT_INTERMEDIAIRE', 'Produit intermédiaire'), ('PRODUIT_FINI', 'Produit fini')], max_length=30, verbose_name="Type d'article")),
                ('unite_mesure', models.CharField(choices=[('KG', 'Kilogramme'), ('L', 'Litre'), ('UNITE', 'Unité'), ('CARTON', 'Carton'), ('PALETTE', 'Palette'), ('M', 'Mètre')], max_length=10, verbose_name='Unité de mesure')),
                ('famille', models.CharField(blank=True, help_text='Ex : Eau, Jus et boissons, Yaourt, Étiquettes', max_length=50, verbose_name='Famille')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FicheConditionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_unites_par_carton', models.PositiveIntegerField(verbose_name='Unités par carton')),
                ('type_emballage', models.CharField(max_length=100, verbose_name="Type d'emballage")),
                ('poids_carton_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Poids du carton (kg)')),
                ('nombre_cartons_par_palette', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cartons par palette')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_conditionnement', to='referentiel.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Fiche de conditionnement',
                'verbose_name_plural': 'Fiches de conditionnement',
            },
        ),
        migrations.CreateModel(
            name='FicheTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('ARCHIVEE', 'Archivée')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches_techniques', to='referentiel.article', verbose_name='Article fabriqué')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiches_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par')),
            ],
            options={
                'verbose_name': 'Fiche technique',
                'verbose_name_plural': 'Fiches techniques',
                'ordering': ['article', '-version'],
                'unique_together': {('article', 'version')},
            },
        ),
        migrations.CreateModel(
            name='CompositionFicheTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_necessaire', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Quantité nécessaire par unité produite')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utilise_dans_fiches', to='referentiel.article', verbose_name='Matière / intrant')),
                ('fiche_technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='referentiel.fichetechnique', verbose_name='Fiche technique')),
            ],
            options={
                'verbose_name': 'Ligne de composition',
                'verbose_name_plural': 'Composition des fiches techniques',
                'unique_together': {('fiche_technique', 'matiere')},
            },
        ),
    ]
