# Generated by Django 6.1 on 2026-09-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0004_fiches_brouillon_produits_finis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='code',
            field=models.CharField(editable=False, help_text='Généré automatiquement selon le type : MP-000001 (matière première), PI-000001 (produit intermédiaire), PF-000001 (produit fini). Jamais saisi.', max_length=30, unique=True, verbose_name='Code article'),
        ),
    ]
