# Generated by Django 6.1 on 2026-09-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0005_codification_automatique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='code',
            field=models.CharField(editable=False, help_text='Généré automatiquement, jamais saisi. Produit fini : famille + parfum + format + unité de vente (ex : EAU70P8, JUSGRE70P8). Matière première / produit intermédiaire : MP-000001 / PI-000001.', max_length=30, unique=True, verbose_name='Code article'),
        ),
    ]
