# Generated by Django 6.1 on 2026-10-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0007_renommer_codes_produits_finis'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositionfichetechnique',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Prix d'une unité de la matière (ex : 1 000 FCFA le litre de ferment). Sert à chiffrer les besoins matières de chaque OF (quantité à produire x quantité nécessaire x prix).", max_digits=14, verbose_name="Prix unitaire de l'élément"),
        ),
    ]
