# Generated by Django 6.1 on 2026-10-06 21:39

import apps.core.validation
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industriel', '0001_initial'),
        ('referentiel', '0008_chiffrage_matieres'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='activite',
            field=models.ForeignKey(blank=True, help_text='Produit fini : déduite de la famille (Eau -> EAU). Sert aux lignes, circuits, contrôles et coûts.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='industriel.activite', verbose_name='Activité'),
        ),
        migrations.AddField(
            model_name='article',
            name='activites_autorisees',
            field=models.ManyToManyField(blank=True, help_text='Un même article (ex : sucre) sert plusieurs activités : on ne le duplique pas. Vide = toutes.', related_name='articles_autorises', to='industriel.activite', verbose_name='Activités autorisées'),
        ),
        migrations.AddField(
            model_name='article',
            name='contenance',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Produit fini : contenu d'une bouteille/pot (0,7 L ; 0,125 kg). Déduit du format si vide.", max_digits=10, null=True, verbose_name='Contenance / poids unitaire'),
        ),
        migrations.AddField(
            model_name='article',
            name='mode_approvisionnement',
            field=models.CharField(blank=True, choices=[('ACHETE', 'Acheté'), ('FABRIQUE', 'Fabriqué'), ('PROCESS', 'Produit par le process')], help_text='Déduit du type si vide : acheté (MP, emballage, consommable), fabriqué (produit fini...).', max_length=10, verbose_name="Mode d'approvisionnement"),
        ),
        migrations.AddField(
            model_name='article',
            name='packs_par_palette',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Packs par palette'),
        ),
        migrations.AddField(
            model_name='article',
            name='type_emballage',
            field=models.CharField(blank=True, help_text='Ex : bouteille PET soufflée sur site, pot, film, carton.', max_length=100, verbose_name="Type d'emballage"),
        ),
        migrations.AddField(
            model_name='article',
            name='unite_achat',
            field=models.CharField(blank=True, choices=[('KG', 'Kilogramme'), ('G', 'Gramme'), ('L', 'Litre'), ('CL', 'Centilitre'), ('M3', 'Mètre cube'), ('UNITE', 'Unité'), ('BOUTEILLE', 'Bouteille'), ('POT', 'Pot'), ('PACK', 'Pack'), ('CARTON', 'Carton'), ('SAC', 'Sac'), ('PALETTE', 'Palette'), ('M', 'Mètre')], help_text='Ex : sac (1 sac = 25 kg, voir les conversions). Vide = unité de base.', max_length=10, verbose_name="Unité d'achat"),
        ),
        migrations.AddField(
            model_name='article',
            name='unite_consommation',
            field=models.CharField(blank=True, choices=[('KG', 'Kilogramme'), ('G', 'Gramme'), ('L', 'Litre'), ('CL', 'Centilitre'), ('M3', 'Mètre cube'), ('UNITE', 'Unité'), ('BOUTEILLE', 'Bouteille'), ('POT', 'Pot'), ('PACK', 'Pack'), ('CARTON', 'Carton'), ('SAC', 'Sac'), ('PALETTE', 'Palette'), ('M', 'Mètre')], help_text='Unité des recettes et des sorties vers la production. Vide = unité de base.', max_length=10, verbose_name='Unité de consommation'),
        ),
        migrations.AddField(
            model_name='article',
            name='unite_contenance',
            field=models.CharField(blank=True, choices=[('L', 'Litre'), ('KG', 'Kilogramme')], max_length=10, verbose_name='Unité de contenance'),
        ),
        migrations.AddField(
            model_name='article',
            name='unites_par_pack',
            field=models.PositiveIntegerField(blank=True, help_text="Bouteilles/pots par pack ou carton (Pack de 6 -> 6). Déduit de l'unité de vente si vide.", null=True, verbose_name='Unités par pack'),
        ),
        migrations.AddField(
            model_name='article',
            name='unites_par_unite_stock',
            field=models.PositiveIntegerField(blank=True, help_text="1 si le stock et les OF comptent des bouteilles ; 6 s'ils comptent des packs de 6. Déduit de l'unité de base si vide (Pack/Carton -> unités par pack, sinon 1).", null=True, verbose_name='Unités (bouteilles/pots) par unité de stock'),
        ),
        migrations.AddField(
            model_name='compositionfichetechnique',
            name='article_format',
            field=models.ForeignKey(blank=True, help_text='Recette partagée : emballage propre à un format (préforme 1,5 L...). Vide = tous les formats.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_composition_specifiques', to='referentiel.article', verbose_name='Uniquement pour le format'),
        ),
        migrations.AddField(
            model_name='compositionfichetechnique',
            name='base_calcul',
            field=models.CharField(choices=[('REFERENCE', 'Quantité de référence de la recette'), ('UNITE', 'Par bouteille / pot produit'), ('PACK', 'Par pack / carton produit')], default='REFERENCE', help_text='Ingrédients : quantité de référence (ex : 100 kg de sucre pour 1 000 L). Emballages : par bouteille (préforme, bouchon) ou par pack (film, carton).', max_length=10, verbose_name='Base de calcul'),
        ),
        migrations.AddField(
            model_name='compositionfichetechnique',
            name='etape',
            field=models.ForeignKey(blank=True, help_text='Ex : préformes au soufflage, film à la plastification (sert au coût par étape).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='industriel.etapestandard', verbose_name='Étape de consommation'),
        ),
        migrations.AddField(
            model_name='compositionfichetechnique',
            name='ordre_incorporation',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'incorporation"),
        ),
        migrations.AddField(
            model_name='compositionfichetechnique',
            name='perte_theorique_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Perte théorique (%)'),
        ),
        migrations.AddField(
            model_name='compositionfichetechnique',
            name='role',
            field=models.CharField(blank=True, help_text='Ex : base, ingrédient, emballage primaire.', max_length=100, verbose_name='Rôle'),
        ),
        migrations.AddField(
            model_name='famillearticle',
            name='activite',
            field=models.ForeignKey(blank=True, help_text='Les produits finis de cette famille appartiennent à cette activité (Eau -> EAU...).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='familles', to='industriel.activite', verbose_name='Activité'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='date_debut_validite',
            field=models.DateField(blank=True, null=True, verbose_name='Valide à partir du'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='date_fin_validite',
            field=models.DateField(blank=True, null=True, verbose_name="Valide jusqu'au"),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='document_reference',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fiche / formulation de référence'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='formats_associes',
            field=models.ManyToManyField(blank=True, help_text='Ex : la recette du jus orange 1 L sert aussi au 70 cl et au 1,5 L (seuls les emballages diffèrent).', related_name='recettes_partagees', to='referentiel.article', verbose_name='Autres formats utilisant cette recette'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='parametres_process',
            field=models.TextField(blank=True, help_text="Températures, temps, agitation... tels qu'ils figurent sur la fiche validée.", verbose_name='Paramètres de process'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='quantite_reference',
            field=models.DecimalField(decimal_places=3, default=1, help_text='La composition est donnée pour cette quantité (ex : 1 000 pour « pour 1 000 L »).', max_digits=12, verbose_name='Quantité de référence'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='rendement_theorique_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ex : 98 -> les besoins de la recette sont majorés de 100/98.', max_digits=5, null=True, verbose_name='Rendement théorique (%)'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='unite_reference',
            field=models.CharField(choices=[('UNITE_STOCK', 'Unité de stock du produit fabriqué'), ('L', 'Litre de produit'), ('KG', 'Kilogramme de produit')], default='UNITE_STOCK', max_length=15, verbose_name='Unité de référence'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type_article',
            field=models.CharField(choices=[('MATIERE_PREMIERE', 'Matière première'), ('PRODUIT_INTERMEDIAIRE', 'Produit intermédiaire'), ('PRODUIT_FINI', 'Produit fini'), ('EMBALLAGE', 'Emballage'), ('CONSOMMABLE', 'Consommable'), ('FLUIDE_PROCESS', 'Fluide de process')], max_length=30, verbose_name="Type d'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='unite_mesure',
            field=models.CharField(choices=[('KG', 'Kilogramme'), ('G', 'Gramme'), ('L', 'Litre'), ('CL', 'Centilitre'), ('M3', 'Mètre cube'), ('UNITE', 'Unité'), ('BOUTEILLE', 'Bouteille'), ('POT', 'Pot'), ('PACK', 'Pack'), ('CARTON', 'Carton'), ('SAC', 'Sac'), ('PALETTE', 'Palette'), ('M', 'Mètre')], help_text='Unité de gestion interne (ex : Unité pour une bouteille).', max_length=10, verbose_name='Unité de base'),
        ),
        migrations.AlterField(
            model_name='compositionfichetechnique',
            name='quantite_necessaire',
            field=models.DecimalField(decimal_places=4, help_text='Pour la quantité de référence de la recette, ou par bouteille/pot ou par pack selon la base de calcul.', max_digits=12, verbose_name='Quantité nécessaire'),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_TEST', 'En test'), ('VALIDEE', 'Validée'), ('ARCHIVEE', 'Remplacée / archivée')], default='BROUILLON', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='ConversionUnite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unite_source', models.CharField(choices=[('KG', 'Kilogramme'), ('G', 'Gramme'), ('L', 'Litre'), ('CL', 'Centilitre'), ('M3', 'Mètre cube'), ('UNITE', 'Unité'), ('BOUTEILLE', 'Bouteille'), ('POT', 'Pot'), ('PACK', 'Pack'), ('CARTON', 'Carton'), ('SAC', 'Sac'), ('PALETTE', 'Palette'), ('M', 'Mètre')], max_length=10, verbose_name='1 unité de')),
                ('facteur', models.DecimalField(decimal_places=6, max_digits=16, verbose_name='vaut')),
                ('unite_cible', models.CharField(choices=[('KG', 'Kilogramme'), ('G', 'Gramme'), ('L', 'Litre'), ('CL', 'Centilitre'), ('M3', 'Mètre cube'), ('UNITE', 'Unité'), ('BOUTEILLE', 'Bouteille'), ('POT', 'Pot'), ('PACK', 'Pack'), ('CARTON', 'Carton'), ('SAC', 'Sac'), ('PALETTE', 'Palette'), ('M', 'Mètre')], max_length=10, verbose_name='unités de')),
                ('article', models.ForeignKey(blank=True, help_text='Vide = conversion générale.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='referentiel.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': "Conversion d'unités",
                'verbose_name_plural': "Conversions d'unités",
                'unique_together': {('article', 'unite_source', 'unite_cible')},
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
    ]
