# Generated by Django 6.1 on 2026-10-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0009_article_activite_article_activites_autorisees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositionfichetechnique',
            name='unite',
            field=models.CharField(blank=True, choices=[('KG', 'Kilogramme'), ('G', 'Gramme'), ('L', 'Litre'), ('CL', 'Centilitre'), ('M3', 'Mètre cube'), ('UNITE', 'Unité'), ('BOUTEILLE', 'Bouteille'), ('POT', 'Pot'), ('PACK', 'Pack'), ('CARTON', 'Carton'), ('SAC', 'Sac'), ('PALETTE', 'Palette'), ('M', 'Mètre')], help_text="Unité de consommation (ex : G pour 20 g de stabilisant). Vide = unité de consommation de l'article, sinon son unité de stock. Les besoins de l'OF sont convertis en unité de stock.", max_length=10, verbose_name='Unité de la quantité'),
        ),
    ]
