# Generated by Django 6.1 on 2026-08-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceNumerotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixe', models.CharField(max_length=10, unique=True, verbose_name='Préfixe')),
                ('dernier_numero', models.PositiveIntegerField(default=0, verbose_name='Dernier numéro utilisé')),
            ],
            options={
                'verbose_name': 'Séquence de numérotation',
                'verbose_name_plural': 'Séquences de numérotation',
            },
        ),
    ]
