# Generated by Django 6.1 on 2026-09-30 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet_id', models.PositiveBigIntegerField(verbose_name='Identifiant du document')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='Référence')),
                ('action', models.CharField(max_length=50, verbose_name='Action')),
                ('ancien_statut', models.CharField(blank=True, max_length=60, verbose_name='Ancien statut')),
                ('nouveau_statut', models.CharField(blank=True, max_length=60, verbose_name='Nouveau statut')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Type de document')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Par')),
            ],
            options={
                'verbose_name': 'Historique de document',
                'verbose_name_plural': 'Historique des documents',
                'ordering': ['date', 'pk'],
                'indexes': [models.Index(fields=['content_type', 'objet_id'], name='core_histor_content_599074_idx')],
            },
        ),
    ]
