# Generated by Django 6.1 on 2026-09-30 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historique_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150, verbose_name='Titre')),
                ('message', models.CharField(blank=True, max_length=500, verbose_name='Message')),
                ('type_document', models.CharField(blank=True, help_text='Ex : caisse.decaissement', max_length=60, verbose_name='Type de document')),
                ('document_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Identifiant du document')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='Référence')),
                ('lue', models.BooleanField(default=False, verbose_name='Lue')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date', '-pk'],
                'indexes': [models.Index(fields=['destinataire', 'lue'], name='core_notifi_destina_7c8e7b_idx')],
            },
        ),
    ]
