# Generated by Django 6.1 on 2026-10-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notifications_anomalies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(default='EVAM', max_length=200, verbose_name='Raison sociale')),
                ('forme_juridique', models.CharField(blank=True, help_text='Ex : SARL, SA.', max_length=50, verbose_name='Forme juridique')),
                ('capital', models.CharField(blank=True, help_text='Ex : 10 000 000 FCFA.', max_length=60, verbose_name='Capital social')),
                ('activite', models.CharField(blank=True, help_text="Ex : Production d'eau, de jus et de yaourt.", max_length=200, verbose_name='Activité')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville / pays')),
                ('telephone', models.CharField(blank=True, max_length=60, verbose_name='Téléphone')),
                ('email', models.CharField(blank=True, max_length=120, verbose_name='Email')),
                ('site_web', models.CharField(blank=True, max_length=120, verbose_name='Site web')),
                ('ifu', models.CharField(blank=True, max_length=30, verbose_name='IFU')),
                ('rccm', models.CharField(blank=True, max_length=60, verbose_name='RCCM')),
                ('regime_fiscal', models.CharField(blank=True, max_length=100, verbose_name='Régime fiscal')),
                ('centre_impots', models.CharField(blank=True, max_length=100, verbose_name='Centre des impôts')),
                ('banque', models.CharField(blank=True, max_length=200, verbose_name='Banque et RIB')),
                ('conditions_paiement', models.TextField(blank=True, verbose_name='Conditions de paiement (factures)')),
                ('mentions_pied_de_page', models.TextField(blank=True, verbose_name='Autres mentions de pied de page')),
                ('couleur', models.CharField(default='#0A6676', help_text='Code hexadécimal, ex : #0A6676.', max_length=7, verbose_name='Couleur des documents')),
                ('logo', models.BinaryField(blank=True, null=True, verbose_name='Logo')),
                ('logo_type', models.CharField(blank=True, editable=False, max_length=30, verbose_name='Type du logo')),
            ],
            options={
                'verbose_name': "Paramètres de l'entreprise (documents)",
                'verbose_name_plural': "Paramètres de l'entreprise (documents)",
            },
        ),
    ]
