# Generated by Django 6.1 on 2026-10-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_documents_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametreentreprise',
            name='sfec_actif',
            field=models.BooleanField(default=False, help_text='À activer quand la société et son accès SFEC sont en place (le jeton reste dans la variable SFEC_JETON).', verbose_name='Certification SFEC active'),
        ),
        migrations.AddField(
            model_name='parametreentreprise',
            name='sfec_nim',
            field=models.CharField(blank=True, max_length=40, verbose_name='NIM (n° de la machine / du point de facturation)'),
        ),
        migrations.AddField(
            model_name='parametreentreprise',
            name='sfec_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse du service SFEC'),
        ),
    ]
