# Generated by Django 6.1 on 2026-10-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comptes_synthese_sfec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencenumerotation',
            name='prefixe',
            field=models.CharField(max_length=40, unique=True, verbose_name='Préfixe'),
        ),
    ]
