# Generated by Django 6.1 on 2026-08-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Prix unitaire négocié')),
                ('delai_livraison_jours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Délai de livraison (jours)')),
                ('reference_fournisseur', models.CharField(blank=True, max_length=100, verbose_name='Référence chez le fournisseur')),
            ],
            options={
                'verbose_name': 'Article fourni par un fournisseur',
                'verbose_name_plural': 'Catalogue des articles fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='BesoinApprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_besoin', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantité nécessaire')),
                ('origine', models.CharField(choices=[('AUTO_PRODUCTION', 'Généré automatiquement par la production'), ('MANUEL', 'Saisi manuellement')], max_length=20, verbose_name='Origine du besoin')),
                ('satisfait', models.BooleanField(default=False, verbose_name='Satisfait par une commande')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': "Besoin d'approvisionnement",
                'verbose_name_plural': "Besoins d'approvisionnement",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYEE', 'Envoyée'), ('PARTIELLEMENT_RECUE', 'Partiellement reçue'), ('RECUE', 'Reçue'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=25, verbose_name='Statut')),
                ('date_commande', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
            ],
            options={
                'verbose_name': 'Commande fournisseur',
                'verbose_name_plural': 'Commandes fournisseurs',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='ContratFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro de contrat')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('conditions', models.TextField(blank=True, help_text='Modalités de paiement, délais de livraison garantis, pénalités, exclusivité...', verbose_name='Conditions particulières')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('RESILIE', 'Résilié'), ('BROUILLON', 'Brouillon')], default='BROUILLON', max_length=15, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Contrat fournisseur',
                'verbose_name_plural': 'Contrats fournisseurs',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='DemandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_demandee', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantité demandée')),
                ('motif', models.TextField(blank=True, verbose_name='Motif')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée'), ('TRANSFORMEE', 'Transformée en commande')], default='EN_ATTENTE', max_length=15, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
            ],
            options={
                'verbose_name': "Demande d'achat",
                'verbose_name_plural': "Demandes d'achat",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code fournisseur')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('contact', models.CharField(blank=True, max_length=150, verbose_name='Contact')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commandee', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantité commandée')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Prix unitaire')),
                ('quantite_recue', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Quantité reçue')),
            ],
            options={
                'verbose_name': 'Ligne de commande fournisseur',
                'verbose_name_plural': 'Lignes de commande fournisseur',
            },
        ),
        migrations.CreateModel(
            name='LigneReceptionAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_recue', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantité reçue')),
            ],
            options={
                'verbose_name': 'Ligne de réception',
                'verbose_name_plural': 'Lignes de réception',
            },
        ),
        migrations.CreateModel(
            name='ReceptionAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conforme', models.BooleanField(default=True, help_text='Contrôle réception : la livraison correspond-elle à la commande ?', verbose_name='Réception conforme')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date_reception', models.DateTimeField(auto_now_add=True, verbose_name='Date de réception')),
            ],
            options={
                'verbose_name': "Réception d'achat",
                'verbose_name_plural': "Réceptions d'achats",
                'ordering': ['-date_reception'],
            },
        ),
        migrations.CreateModel(
            name='RetourFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_retournee', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantité retournée')),
                ('motif', models.CharField(choices=[('NON_CONFORME', 'Non conforme'), ('ENDOMMAGE', 'Endommagé au transport'), ('QUANTITE_EXCEDENTAIRE', 'Quantité excédentaire livrée'), ('ERREUR_REFERENCE', 'Erreur de référence'), ('AUTRE', 'Autre')], max_length=25, verbose_name='Motif')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date_retour', models.DateTimeField(auto_now_add=True, verbose_name='Date de retour')),
            ],
            options={
                'verbose_name': 'Retour fournisseur',
                'verbose_name_plural': 'Retours fournisseurs',
                'ordering': ['-date_retour'],
            },
        ),
    ]
