# Generated by Django 6.1 on 2026-08-23 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achats', '0001_initial'),
        ('referentiel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articlefournisseur',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs_disponibles', to='referentiel.article', verbose_name='Article fourni'),
        ),
        migrations.AddField(
            model_name='besoinapprovisionnement',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.article', verbose_name='Article'),
        ),
        migrations.AddField(
            model_name='commandefournisseur',
            name='cree_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_fournisseurs_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par (Responsable Achat)'),
        ),
        migrations.AddField(
            model_name='contratfournisseur',
            name='gere_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats_fournisseurs_geres', to=settings.AUTH_USER_MODEL, verbose_name='Négocié par (Responsable Achat)'),
        ),
        migrations.AddField(
            model_name='articlefournisseur',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_couverts', to='achats.contratfournisseur', verbose_name='Contrat associé'),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='approuve_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_achat_approuvees', to=settings.AUTH_USER_MODEL, verbose_name='Approuvée par (Responsable Achat)'),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.article', verbose_name='Article demandé'),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='besoin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_achat', to='achats.besoinapprovisionnement', verbose_name="Besoin d'origine"),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_achat_emises', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur'),
        ),
        migrations.AddField(
            model_name='commandefournisseur',
            name='demande_achat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='achats.demandeachat', verbose_name="Demande d'achat d'origine"),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='gere_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fournisseurs_geres', to=settings.AUTH_USER_MODEL, verbose_name='Géré par (Responsable Achat)'),
        ),
        migrations.AddField(
            model_name='contratfournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='achats.fournisseur', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='commandefournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='achats.fournisseur', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='articlefournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_fournis', to='achats.fournisseur', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='lignecommandefournisseur',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.article', verbose_name='Article'),
        ),
        migrations.AddField(
            model_name='lignecommandefournisseur',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.commandefournisseur', verbose_name='Commande'),
        ),
        migrations.AddField(
            model_name='lignereceptionachat',
            name='ligne_commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_reception', to='achats.lignecommandefournisseur', verbose_name='Ligne de commande'),
        ),
        migrations.AddField(
            model_name='receptionachat',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='achats.commandefournisseur', verbose_name='Commande'),
        ),
        migrations.AddField(
            model_name='receptionachat',
            name='receptionne_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Réceptionné par'),
        ),
        migrations.AddField(
            model_name='lignereceptionachat',
            name='reception',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.receptionachat', verbose_name='Réception'),
        ),
        migrations.AddField(
            model_name='retourfournisseur',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.article', verbose_name='Article retourné'),
        ),
        migrations.AddField(
            model_name='retourfournisseur',
            name='reception',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours', to='achats.receptionachat', verbose_name='Réception concernée'),
        ),
        migrations.AddField(
            model_name='retourfournisseur',
            name='traite_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Traité par'),
        ),
        migrations.AlterUniqueTogether(
            name='articlefournisseur',
            unique_together={('fournisseur', 'article')},
        ),
    ]
