# Generated by Django 6.1 on 2026-09-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='code',
            field=models.CharField(editable=False, help_text='Généré automatiquement (FRS-000001...), jamais saisi.', max_length=30, unique=True, verbose_name='Code fournisseur'),
        ),
    ]
