# Generated by Django 6.1 on 2026-09-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0003_codification_automatique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besoinapprovisionnement',
            name='origine',
            field=models.CharField(choices=[('AUTO_PRODUCTION', 'Généré automatiquement par la production'), ('SEUIL_ALERTE', "Stock passé sous le seuil d'alerte"), ('MANUEL', 'Saisi manuellement')], max_length=20, verbose_name='Origine du besoin'),
        ),
    ]
