# Generated by Django 6.1 on 2026-10-06 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0004_besoin_seuil_alerte'),
        ('stocks', '0003_valorisation_cmup'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignereceptionachat',
            name='date_peremption',
            field=models.DateField(blank=True, null=True, verbose_name='DLC / DLUO'),
        ),
        migrations.AddField(
            model_name='lignereceptionachat',
            name='lot_fournisseur',
            field=models.CharField(blank=True, max_length=60, verbose_name='N° lot fournisseur'),
        ),
        migrations.AddField(
            model_name='receptionachat',
            name='depot',
            field=models.ForeignKey(blank=True, help_text='Vide = « Magasin principal ».', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receptions_achats', to='stocks.depot', verbose_name='Lieu de réception'),
        ),
        migrations.AlterField(
            model_name='receptionachat',
            name='conforme',
            field=models.BooleanField(default=True, help_text='Contrôle réception : la livraison correspond-elle à la commande ? Non conforme = lots bloqués.', verbose_name='Réception conforme'),
        ),
    ]
