# Generated by Django 6.1 on 2026-10-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0005_lignereceptionachat_date_peremption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='ifu',
            field=models.CharField(blank=True, max_length=30, verbose_name='IFU'),
        ),
    ]
