# Generated by Django 6.1 on 2026-10-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0006_documents_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommandefournisseur',
            name='unite',
            field=models.CharField(blank=True, default='', help_text="Unité d'achat (ex : SAC). Vide = unité d'achat de l'article, sinon son unité de stock. Quantités et prix de la ligne sont dans cette unité ; le stock est converti à la réception.", max_length=10, verbose_name='Unité de commande'),
        ),
        migrations.AlterField(
            model_name='retourfournisseur',
            name='quantite_retournee',
            field=models.DecimalField(decimal_places=3, help_text="Dans l'unité de la commande (ex : sacs), comme la quantité reçue.", max_digits=14, verbose_name='Quantité retournée'),
        ),
    ]
