# Generated by Django 6.1 on 2026-08-23 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        ('referentiel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro de lot')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFORME', 'Conforme'), ('NON_CONFORME', 'Non conforme'), ('BLOQUE', 'Bloqué'), ('LIBERE', 'Libéré')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_production', models.DateField(verbose_name='Date de production')),
                ('date_peremption', models.DateField(blank=True, null=True, verbose_name='Date de péremption')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='referentiel.article', verbose_name='Article')),
                ('ordre_fabrication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='production.ordrefabrication', verbose_name='Ordre de fabrication')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ControleQualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat', models.CharField(choices=[('CONFORME', 'Conforme'), ('NON_CONFORME', 'Non conforme')], max_length=20, verbose_name='Résultat')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date_controle', models.DateTimeField(auto_now_add=True, verbose_name='Date de contrôle')),
                ('controleur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Contrôlé par')),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controle_qualite', to='qualite.lot', verbose_name='Lot contrôlé')),
            ],
            options={
                'verbose_name': 'Contrôle qualité',
                'verbose_name_plural': 'Contrôles qualité',
            },
        ),
    ]
