# Generated by Django 6.1 on 2026-10-06 21:39

import apps.core.validation
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualite', '0001_initial'),
        ('stocks', '0003_valorisation_cmup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Code')),
                ('designation', models.CharField(max_length=100, verbose_name='Désignation')),
                ('numero_serie', models.CharField(blank=True, max_length=60, verbose_name='N° appareil / série')),
                ('laboratoire', models.CharField(choices=[('LIGNE', 'Sur ligne (opérateur)'), ('INTERNE', 'Laboratoire interne'), ('EXTERNE', 'Laboratoire externe')], default='LIGNE', max_length=10, verbose_name='Utilisé')),
                ('date_dernier_etalonnage', models.DateField(blank=True, null=True, verbose_name='Dernier étalonnage / vérification')),
                ('periodicite_etalonnage_jours', models.PositiveIntegerField(blank=True, help_text="Vide = pas d'étalonnage suivi.", null=True, verbose_name="Périodicité d'étalonnage (jours)")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Instrument de mesure',
                'verbose_name_plural': 'Instruments de mesure',
                'ordering': ['code'],
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
        migrations.CreateModel(
            name='ParametreQualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=100, verbose_name='Paramètre')),
                ('famille', models.CharField(choices=[('PHYSICO_CHIMIQUE', 'Physico-chimique'), ('MICROBIOLOGIQUE', 'Microbiologique'), ('ORGANOLEPTIQUE', 'Organoleptique (aspect, couleur, goût)'), ('PROCESS', 'Paramètre de process (débit, pression, température...)'), ('CONDITIONNEMENT', 'Conditionnement (volume, bouchage, étiquetage, pack)'), ('MATIERE', 'Matière / réception'), ('DOCUMENTAIRE', 'Documentaire (documents fournisseur...)')], max_length=20, verbose_name='Famille')),
                ('type_resultat', models.CharField(choices=[('NUMERIQUE', 'Valeur mesurée'), ('QUALITATIF', 'Conforme / non conforme')], default='NUMERIQUE', max_length=12, verbose_name='Type de résultat')),
                ('unite', models.CharField(blank=True, help_text='Ex : pH, °Brix, °C, mL, N·m, UFC/mL.', max_length=30, verbose_name='Unité')),
                ('methode', models.CharField(blank=True, max_length=200, verbose_name='Méthode par défaut')),
                ('poids_analyse', models.DecimalField(decimal_places=2, default=1, help_text="Clé « analyses pondérées » du coût laboratoire : une analyse microbiologique pèse plus qu'un pH.", max_digits=8, verbose_name="Poids de l'analyse")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Paramètre qualité',
                'verbose_name_plural': 'Paramètres qualité',
                'ordering': ['famille', 'libelle'],
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
        migrations.CreateModel(
            name='PieceJointeQualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='qualite/%Y/%m', verbose_name='Fichier')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
            ],
            options={
                'verbose_name': 'Pièce jointe qualité',
                'verbose_name_plural': 'Pièces jointes qualité',
            },
        ),
        migrations.CreateModel(
            name='PointControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Code du contrôle')),
                ('designation', models.CharField(max_length=150, verbose_name='Désignation')),
                ('point_prelevement', models.CharField(blank=True, help_text='Ex : avant filtration, sortie UV, cuve tampon.', max_length=150, verbose_name='Point de prélèvement')),
                ('valeur_cible', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Valeur cible')),
                ('valeur_min', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Valeur minimale')),
                ('valeur_max', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Valeur maximale')),
                ('tolerance', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Tolérance (±)')),
                ('bloquant', models.BooleanField(default=False, help_text="Un résultat non conforme bloque le lot et empêche la clôture de l'OF tant que la NC n'est pas traitée.", verbose_name='Contrôle bloquant')),
                ('declencheur', models.CharField(choices=[('RECEPTION', 'À la réception (lot matière)'), ('DEMARRAGE', "Au démarrage de l'OF"), ('CHAQUE_OF', 'Une fois par OF'), ('CHAQUE_LOT', 'À chaque lot de produit fini'), ('PERIODIQUE', 'Toutes les X minutes pendant la production'), ('CHANGEMENT_SERIE', 'Après chaque changement de série'), ('PONCTUEL', 'Ponctuel (à la demande)')], max_length=20, verbose_name='Fréquence / déclenchement')),
                ('frequence_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Toutes les (minutes)')),
                ('type_echantillon', models.CharField(blank=True, max_length=100, verbose_name="Type d'échantillon")),
                ('quantite_echantillon', models.CharField(blank=True, max_length=50, verbose_name="Quantité d'échantillon")),
                ('nombre_echantillons', models.PositiveIntegerField(default=1, verbose_name="Nombre d'échantillons")),
                ('echantillon_conserve', models.BooleanField(default=False, verbose_name='Échantillon témoin conservé')),
                ('methode', models.CharField(blank=True, max_length=200, verbose_name='Méthode')),
                ('laboratoire', models.CharField(choices=[('LIGNE', 'Sur ligne (opérateur)'), ('INTERNE', 'Laboratoire interne'), ('EXTERNE', 'Laboratoire externe')], default='LIGNE', max_length=10, verbose_name='Réalisé')),
                ('actions_si_non_conforme', models.TextField(blank=True, help_text='Ex : arrêt, nouveau contrôle, contre-analyse, réglage machine, blocage lot, rejet, quarantaine.', verbose_name='Actions en cas de non-conformité')),
                ('document_reference', models.CharField(blank=True, max_length=200, verbose_name='Procédure / fiche de référence')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='BROUILLON', max_length=10, verbose_name='Statut')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Applicable à partir du')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name="Applicable jusqu'au")),
            ],
            options={
                'verbose_name': 'Point du plan de contrôle',
                'verbose_name_plural': 'Plan de contrôle',
                'ordering': ['activite', 'etape__ordre_reference', 'code'],
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
        migrations.CreateModel(
            name='ResultatControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='N° contrôle')),
                ('statut', models.CharField(choices=[('A_REALISER', 'À réaliser'), ('EN_ATTENTE_VALIDATION', 'En attente de validation (laboratoire)'), ('CONFORME', 'Conforme'), ('NON_CONFORME', 'Non conforme'), ('ANNULE', 'Annulé')], default='A_REALISER', max_length=25, verbose_name='Statut')),
                ('date_prevue', models.DateTimeField(blank=True, null=True, verbose_name='Prévu le')),
                ('date_realisation', models.DateTimeField(blank=True, null=True, verbose_name='Réalisé le')),
                ('valeur', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Valeur mesurée')),
                ('resultat_qualitatif', models.CharField(blank=True, choices=[('CONFORME', 'Conforme'), ('NON_CONFORME', 'Non conforme')], help_text='Pour un contrôle visuel / qualitatif.', max_length=15, verbose_name='Résultat observé')),
                ('conforme', models.BooleanField(blank=True, editable=False, null=True, verbose_name='Conforme')),
                ('reference_echantillon', models.CharField(blank=True, max_length=60, verbose_name="Référence de l'échantillon")),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('est_reprise', models.BooleanField(default=False, verbose_name='Contrôle de reprise')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Contrôle qualité réalisé',
                'verbose_name_plural': 'Contrôles qualité réalisés',
                'ordering': ['-date_prevue', '-pk'],
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
        migrations.AddField(
            model_name='lot',
            name='depot',
            field=models.ForeignKey(blank=True, editable=False, help_text="Stock usine où le lot entre à sa libération (celui de l'usine de l'OF).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots_produits_finis', to='stocks.depot', verbose_name='Stock produits finis'),
        ),
        migrations.CreateModel(
            name='NonConformite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='N° NC')),
                ('description', models.TextField(verbose_name='Description')),
                ('bloquante', models.BooleanField(default=False, verbose_name='Bloquante')),
                ('cause', models.TextField(blank=True, verbose_name='Cause')),
                ('action_immediate', models.CharField(blank=True, choices=[('ALERTE', 'Alerte'), ('ARRET', 'Arrêt production'), ('BLOCAGE_LOT', 'Blocage du lot'), ('NOUVEAU_CONTROLE', 'Nouveau contrôle'), ('CONTRE_ANALYSE', 'Contre-analyse'), ('REGLAGE', 'Réglage machine'), ('NETTOYAGE', 'Nettoyage / désinfection'), ('CORRECTION_FORMULATION', 'Correction de formulation'), ('QUARANTAINE', 'Quarantaine')], max_length=25, verbose_name='Action immédiate')),
                ('action_corrective', models.TextField(blank=True, verbose_name='Action corrective')),
                ('echeance', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('EN_COURS', 'Action en cours'), ('CLOTUREE', 'Clôturée')], default='OUVERTE', max_length=10, verbose_name='Statut')),
                ('decision', models.CharField(blank=True, choices=[('LIBERATION', 'Libération (reprise conforme)'), ('REPRISE', 'Reprise / retraitement'), ('REJET', 'Rejet'), ('QUARANTAINE', 'Maintien en quarantaine')], max_length=15, verbose_name='Décision')),
                ('date_ouverture', models.DateTimeField(auto_now_add=True, verbose_name='Ouverte le')),
                ('date_cloture', models.DateTimeField(blank=True, null=True, verbose_name='Clôturée le')),
                ('cloturee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nc_cloturees', to=settings.AUTH_USER_MODEL, verbose_name='Clôturée par')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='non_conformites', to='qualite.lot', verbose_name='Lot produit fini')),
            ],
            options={
                'verbose_name': 'Non-conformité',
                'verbose_name_plural': 'Non-conformités',
                'ordering': ['-date_ouverture'],
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
    ]
