# Generated by Django 6.1 on 2026-10-06 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industriel', '0001_initial'),
        ('production', '0007_sortiematiere_lot_matiere_and_more'),
        ('qualite', '0002_instrument_parametrequalite_piecejointequalite_and_more'),
        ('referentiel', '0009_article_activite_article_activites_autorisees_and_more'),
        ('stocks', '0004_depot_activite_depot_articles_autorises_depot_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformite',
            name='lot_matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='non_conformites', to='stocks.lotmatiere', verbose_name='Lot matière'),
        ),
        migrations.AddField(
            model_name='nonconformite',
            name='ordre_fabrication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='non_conformites', to='production.ordrefabrication', verbose_name='OF'),
        ),
        migrations.AddField(
            model_name='nonconformite',
            name='ouverte_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nc_ouvertes', to=settings.AUTH_USER_MODEL, verbose_name='Ouverte par'),
        ),
        migrations.AddField(
            model_name='nonconformite',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nc_a_traiter', to=settings.AUTH_USER_MODEL, verbose_name="Responsable de l'action"),
        ),
        migrations.AddField(
            model_name='piecejointequalite',
            name='ajoute_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par'),
        ),
        migrations.AddField(
            model_name='piecejointequalite',
            name='non_conformite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pieces_jointes', to='qualite.nonconformite', verbose_name='Non-conformité'),
        ),
        migrations.AddField(
            model_name='pointcontrole',
            name='activite',
            field=models.ForeignKey(blank=True, help_text='Vide uniquement pour un contrôle de réception de matière.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='points_controle', to='industriel.activite', verbose_name='Activité'),
        ),
        migrations.AddField(
            model_name='pointcontrole',
            name='article',
            field=models.ForeignKey(blank=True, help_text="Vide = tous les formats de l'activité.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='points_controle', to='referentiel.article', verbose_name='Produit / format ou matière'),
        ),
        migrations.AddField(
            model_name='pointcontrole',
            name='equipement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='industriel.equipement', verbose_name='Machine / équipement (forage, cuve...)'),
        ),
        migrations.AddField(
            model_name='pointcontrole',
            name='etape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='points_controle', to='industriel.etapestandard', verbose_name='Étape du circuit'),
        ),
        migrations.AddField(
            model_name='pointcontrole',
            name='fiche_technique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='points_controle', to='referentiel.fichetechnique', verbose_name='Recette (version)'),
        ),
        migrations.AddField(
            model_name='pointcontrole',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='points', to='qualite.instrument', verbose_name='Instrument'),
        ),
        migrations.AddField(
            model_name='pointcontrole',
            name='parametre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points', to='qualite.parametrequalite', verbose_name='Paramètre contrôlé'),
        ),
        migrations.AddField(
            model_name='pointcontrole',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='industriel.poste', verbose_name='Poste'),
        ),
        migrations.AddField(
            model_name='resultatcontrole',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='referentiel.article', verbose_name='Produit / matière'),
        ),
        migrations.AddField(
            model_name='resultatcontrole',
            name='controle_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reprises', to='qualite.resultatcontrole', verbose_name="Contrôle d'origine (reprise)"),
        ),
        migrations.AddField(
            model_name='resultatcontrole',
            name='equipement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='industriel.equipement', verbose_name='Machine'),
        ),
        migrations.AddField(
            model_name='resultatcontrole',
            name='etape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='industriel.etapestandard', verbose_name='Étape'),
        ),
        migrations.AddField(
            model_name='resultatcontrole',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='qualite.instrument', verbose_name='Instrument utilisé'),
        ),
        migrations.AddField(
            model_name='resultatcontrole',
            name='ligne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='industriel.ligne', verbose_name='Ligne'),
        ),
        migrations.AddField(
            model_name='resultatcontrole',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultats_controles', to='qualite.lot', verbose_name='Lot produit fini'),
        ),
        migrations.AddField(
            model_name='resultatcontrole',
            name='lot_matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultats_controles', to='stocks.lotmatiere', verbose_name='Lot matière / emballage'),
        ),
        migrations.AddField(
            model_name='resultatcontrole',
            name='operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controles_realises', to=settings.AUTH_USER_MODEL, verbose_name='Opérateur'),
        ),
        migrations.AddField(
            model_name='resultatcontrole',
            name='ordre_fabrication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controles_qualite', to='production.ordrefabrication', verbose_name='OF'),
        ),
        migrations.AddField(
            model_name='resultatcontrole',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats', to='qualite.pointcontrole', verbose_name='Contrôle (plan)'),
        ),
        migrations.AddField(
            model_name='resultatcontrole',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='industriel.poste', verbose_name='Poste'),
        ),
        migrations.AddField(
            model_name='resultatcontrole',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controles_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par (qualité)'),
        ),
        migrations.AddField(
            model_name='piecejointequalite',
            name='resultat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pieces_jointes', to='qualite.resultatcontrole', verbose_name='Contrôle'),
        ),
        migrations.AddField(
            model_name='nonconformite',
            name='resultat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='non_conformites', to='qualite.resultatcontrole', verbose_name="Contrôle à l'origine"),
        ),
    ]
