# Generated by Django 6.1 on 2026-10-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualite', '0004_pieces_jointes_en_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointcontrole',
            name='frequence_quantite',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Contrôle « par quantité » : quantité produite à l'étape du contrôle (unités, litres ou m³ selon la saisie de l'étape), ex : tous les 5 000 bouteilles, tous les 10 m³.", max_digits=14, null=True, verbose_name='Toutes les (quantité)'),
        ),
        migrations.AlterField(
            model_name='pointcontrole',
            name='declencheur',
            field=models.CharField(choices=[('RECEPTION', 'À la réception (lot matière)'), ('DEMARRAGE', "Au démarrage de l'OF"), ('CHAQUE_OF', 'Une fois par OF'), ('CHAQUE_LOT', 'À chaque lot de produit fini'), ('PERIODIQUE', 'Toutes les X minutes pendant la production'), ('PAR_QUANTITE', 'Toutes les X unités / litres produits (ou m³ traités)'), ('CHAQUE_CUVE', 'À chaque cuve préparée'), ('CHANGEMENT_SERIE', 'Après chaque changement de série'), ('APRES_NETTOYAGE', 'Après nettoyage / désinfection'), ('APRES_ARRET', 'Après arrêt / redémarrage'), ('PONCTUEL', 'Ponctuel (à la demande)')], max_length=20, verbose_name='Fréquence / déclenchement'),
        ),
    ]
