# Generated by Django 6.1 on 2026-10-07 20:30

import apps.core.validation
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industriel', '0003_ajustements_questionnaire'),
        ('qualite', '0005_tracabilite_palettes_declencheurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='activite',
            field=models.ForeignKey(blank=True, help_text='Vide = commun à toutes les activités.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='industriel.activite', verbose_name='Activité'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='grandeur_mesuree',
            field=models.CharField(blank=True, help_text='Ex : pH, °Brix, température, couple.', max_length=60, verbose_name='Mesure'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='type_instrument',
            field=models.CharField(blank=True, help_text="Ex : pH-mètre, réfractomètre, thermomètre / sonde, conductimètre, balance, débitmètre, couplemètre, pied à coulisse / jauge, testeur d'étanchéité, matériel de laboratoire.", max_length=60, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='unite',
            field=models.CharField(blank=True, max_length=30, verbose_name='Unité'),
        ),
        migrations.AddField(
            model_name='pointcontrole',
            name='obligatoire',
            field=models.BooleanField(default=False, help_text="Q44 : tant qu'il n'est pas réalisé, le lot ne peut pas être libéré (ni l'OF clôturé).", verbose_name='Contrôle obligatoire'),
        ),
        migrations.AlterField(
            model_name='pointcontrole',
            name='designation',
            field=models.CharField(blank=True, max_length=150, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='pointcontrole',
            name='parametre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='points', to='qualite.parametrequalite', verbose_name='Paramètre contrôlé'),
        ),
        migrations.CreateModel(
            name='ModeleControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Code')),
                ('designation', models.CharField(max_length=150, verbose_name='Désignation')),
                ('methode', models.CharField(blank=True, max_length=200, verbose_name='Méthode')),
                ('laboratoire', models.CharField(choices=[('LIGNE', 'Sur ligne (opérateur)'), ('INTERNE', 'Laboratoire interne'), ('EXTERNE', 'Laboratoire externe')], default='LIGNE', max_length=10, verbose_name='Réalisé')),
                ('type_echantillon', models.CharField(blank=True, max_length=100, verbose_name="Type d'échantillon")),
                ('quantite_echantillon', models.CharField(blank=True, max_length=50, verbose_name="Quantité d'échantillon")),
                ('nombre_echantillons', models.PositiveIntegerField(default=1, verbose_name="Nombre d'échantillons")),
                ('obligatoire', models.BooleanField(default=False, verbose_name='Obligatoire par défaut')),
                ('bloquant', models.BooleanField(default=False, verbose_name='Bloquant par défaut')),
                ('actions_si_non_conforme', models.TextField(blank=True, verbose_name='Actions en cas de non-conformité')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modeles', to='qualite.instrument', verbose_name='Instrument')),
                ('parametre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modeles', to='qualite.parametrequalite', verbose_name='Paramètre')),
            ],
            options={
                'verbose_name': 'Modèle de contrôle (bibliothèque)',
                'verbose_name_plural': 'Bibliothèque de contrôles',
                'ordering': ['designation'],
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
        migrations.AddField(
            model_name='pointcontrole',
            name='modele',
            field=models.ForeignKey(blank=True, help_text='Les valeurs du modèle (paramètre, instrument, méthode, échantillon...) sont reprises à la création.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='points', to='qualite.modelecontrole', verbose_name='Créé depuis le modèle'),
        ),
    ]
