# Generated by Django 6.1 on 2026-08-23 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Dépôt (distribution)',
                'verbose_name_plural': 'Dépôts (distribution)',
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=30, unique=True, verbose_name='Immatriculation')),
                ('type_vehicule', models.CharField(blank=True, max_length=100, verbose_name='Type de véhicule')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
            },
        ),
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permis_numero', models.CharField(blank=True, max_length=50, verbose_name='Numéro de permis')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_chauffeur', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Chauffeur',
                'verbose_name_plural': 'Chauffeurs',
            },
        ),
        migrations.CreateModel(
            name='PreparationLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('A_PREPARER', 'À préparer'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('SORTIE_MAGASIN', 'Sortie magasin')], default='A_PREPARER', max_length=20, verbose_name='Statut')),
                ('date_lancement', models.DateTimeField(auto_now_add=True, verbose_name='Date de lancement')),
                ('date_confirmation_sortie', models.DateTimeField(blank=True, null=True, verbose_name='Date de sortie magasin')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='preparation', to='commercial.commande', verbose_name='Commande')),
                ('lancee_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparations_lancees', to=settings.AUTH_USER_MODEL, verbose_name='Préparation lancée par (Resp. Distribution)')),
                ('preparee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparations_faites', to=settings.AUTH_USER_MODEL, verbose_name='Préparée par (Magasinier)')),
            ],
            options={
                'verbose_name': 'Préparation de livraison',
                'verbose_name_plural': 'Préparations de livraison',
            },
        ),
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro')),
                ('date_tournee', models.DateField(verbose_name='Date de la tournée')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='distribution.chauffeur', verbose_name='Chauffeur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='distribution.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Tournée',
                'verbose_name_plural': 'Tournées',
            },
        ),
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro BL')),
                ('statut', models.CharField(choices=[('EN_LIVRAISON', 'En livraison'), ('LIVREE', 'Livrée'), ('PARTIELLEMENT_LIVREE', 'Partiellement livrée'), ('RETOURNEE', 'Retournée')], default='EN_LIVRAISON', max_length=25, verbose_name='Statut')),
                ('signature_client', models.BooleanField(default=False, verbose_name='Signé par le client')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('date_livraison', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bon_livraison', to='commercial.commande', verbose_name='Commande')),
                ('confirme_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='livraisons_confirmees', to=settings.AUTH_USER_MODEL, verbose_name='Livraison confirmée par (Resp. Distribution)')),
                ('tournee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distribution.tournee', verbose_name='Tournée')),
            ],
            options={
                'verbose_name': 'Bon de livraison',
                'verbose_name_plural': 'Bons de livraison',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='TransfertDepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transfert', models.DateTimeField(auto_now_add=True, verbose_name='Date de transfert')),
                ('statut', models.CharField(default='EN_COURS', max_length=20, verbose_name='Statut')),
                ('depot_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_entrants', to='distribution.depot', verbose_name='Dépôt destination')),
                ('depot_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_sortants', to='distribution.depot', verbose_name='Dépôt source')),
            ],
            options={
                'verbose_name': 'Transfert entre dépôts',
                'verbose_name_plural': 'Transferts entre dépôts',
            },
        ),
    ]
