# Generated by Django 6.1 on 2026-09-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonlivraison',
            name='date_signature',
            field=models.DateTimeField(blank=True, help_text='Renseignée par le chauffeur (action « Livré »).', null=True, verbose_name='Date de remise au client'),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='incident_livraison',
            field=models.TextField(blank=True, help_text='Renseigné par le chauffeur (action « Problème ») : client absent, refus, casse...', verbose_name='Problème signalé'),
        ),
    ]
