# Generated by Django 6.1 on 2026-10-06 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_chauffeur_livraison'),
        ('stocks', '0003_valorisation_cmup'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparationlivraison',
            name='depot',
            field=models.ForeignKey(blank=True, help_text='Stock usine ou dépôt extérieur. Vide = « Dépôt produits finis ».', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparations', to='stocks.depot', verbose_name='Lieu de sortie'),
        ),
        migrations.AddField(
            model_name='tournee',
            name='kilometrage_depart',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Compteur au départ (km)'),
        ),
        migrations.AddField(
            model_name='tournee',
            name='kilometrage_retour',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Compteur au retour (km)'),
        ),
    ]
