# Generated by Django 6.1 on 2026-08-23 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du dépôt')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Dépôt',
                'verbose_name_plural': 'Dépôts',
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inventaire', models.DateField(verbose_name="Date de l'inventaire")),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('CLOTURE', 'Clôturé')], default='EN_COURS', max_length=20, verbose_name='Statut')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Réalisé par')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.depot', verbose_name='Dépôt')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
            },
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_theorique', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantité théorique')),
                ('quantite_comptee', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantité comptée')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.article', verbose_name='Article')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stocks.inventaire', verbose_name='Inventaire')),
            ],
            options={
                'verbose_name': "Ligne d'inventaire",
                'verbose_name_plural': "Lignes d'inventaire",
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('TRANSFERT', 'Transfert'), ('AJUSTEMENT', 'Ajustement (inventaire)'), ('RETOUR', 'Retour')], max_length=20, verbose_name='Type de mouvement')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantité')),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='Motif')),
                ('document_origine', models.CharField(blank=True, help_text="Ex : numéro d'OF, de commande, de bon de livraison à l'origine du mouvement.", max_length=100, verbose_name="Document d'origine")),
                ('date_mouvement', models.DateTimeField(auto_now_add=True, verbose_name='Date du mouvement')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='referentiel.article', verbose_name='Article')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='stocks.depot', verbose_name='Dépôt')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.CreateModel(
            name='StockArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_physique', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Quantité physique')),
                ('quantite_bloquee', models.DecimalField(decimal_places=3, default=0, help_text='Ex : lots non conformes en attente de décision qualité.', max_digits=14, verbose_name='Quantité bloquée')),
                ('quantite_reservee', models.DecimalField(decimal_places=3, default=0, help_text='Ex : réservée pour une commande client validée non encore livrée.', max_digits=14, verbose_name='Quantité réservée')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='referentiel.article', verbose_name='Article')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='stocks.depot', verbose_name='Dépôt')),
            ],
            options={
                'verbose_name': 'Stock par article',
                'verbose_name_plural': 'Stocks par article',
                'unique_together': {('article', 'depot')},
            },
        ),
    ]
