# Generated by Django 6.1 on 2026-09-30 13:43

import django.db.models.deletion
from django.db import migrations, models


def valoriser_stock_existant(apps, schema_editor):
    """
    Stock déjà en base : son coût de départ est le dernier coût matière
    valorisé par la DAF, sinon le dernier coût standard, sinon 0 (à
    compléter ensuite par la DAF via les coûts matières).
    """
    StockArticle = apps.get_model("stocks", "StockArticle")
    ValorisationArticle = apps.get_model("stocks", "ValorisationArticle")
    CoutMatiere = apps.get_model("couts", "CoutMatiere")
    CoutStandard = apps.get_model("couts", "CoutStandard")
    for article_id in StockArticle.objects.values_list("article_id", flat=True).distinct():
        cout = CoutMatiere.objects.filter(article_id=article_id).order_by("-date_valorisation").first()
        if cout:
            valeur = cout.cout_unitaire
        else:
            standard = CoutStandard.objects.filter(article_id=article_id).order_by("-date_debut_validite").first()
            valeur = standard.cout_standard_unitaire if standard else 0
        ValorisationArticle.objects.get_or_create(article_id=article_id, defaults={"cout_unitaire_moyen": valeur})


class Migration(migrations.Migration):

    dependencies = [
        ('couts', '0001_initial'),
        ('referentiel', '0007_renommer_codes_produits_finis'),
        ('stocks', '0002_depots_systeme'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='cout_unitaire',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Entrée : coût réel (prix d'achat, coût de revient de l'OF) ou, à défaut, coût moyen. Sortie : toujours le coût moyen pondéré (CMUP) du moment.", max_digits=14, null=True, verbose_name='Coût unitaire'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='valeur',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=16, null=True, verbose_name='Valeur'),
        ),
        migrations.CreateModel(
            name='ValorisationArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_unitaire_moyen', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Coût moyen unitaire pondéré')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valorisation', to='referentiel.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': "Valorisation d'article (CMUP)",
                'verbose_name_plural': "Valorisations d'articles (CMUP)",
            },
        ),
        migrations.RunPython(valoriser_stock_existant, migrations.RunPython.noop),
    ]
