# Generated by Django 6.1 on 2026-10-06 21:39

import apps.core.validation
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0005_lignereceptionachat_date_peremption_and_more'),
        ('industriel', '0001_initial'),
        ('qualite', '0002_instrument_parametrequalite_piecejointequalite_and_more'),
        ('referentiel', '0009_article_activite_article_activites_autorisees_and_more'),
        ('stocks', '0003_valorisation_cmup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='activite',
            field=models.ForeignKey(blank=True, help_text='Vide = toutes activités.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lieux_stockage', to='industriel.activite', verbose_name='Activité'),
        ),
        migrations.AddField(
            model_name='depot',
            name='articles_autorises',
            field=models.ManyToManyField(blank=True, help_text='Vide = tous les articles.', related_name='lieux_autorises', to='referentiel.article', verbose_name='Articles autorisés'),
        ),
        migrations.AddField(
            model_name='depot',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='depot',
            name='gestion_lots',
            field=models.BooleanField(default=True, verbose_name='Gestion des lots'),
        ),
        migrations.AddField(
            model_name='depot',
            name='type_lieu',
            field=models.CharField(choices=[('MAGASIN_MATIERES', 'Magasin matières (usine)'), ('STOCK_USINE', 'Stock usine (produits finis)'), ('DEPOT_EXTERIEUR', 'Dépôt extérieur / point de vente'), ('QUARANTAINE', 'Quarantaine')], default='DEPOT_EXTERIEUR', max_length=20, verbose_name='Type de lieu'),
        ),
        migrations.AddField(
            model_name='depot',
            name='usine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lieux_stockage', to='industriel.usine', verbose_name='Usine de rattachement'),
        ),
        migrations.CreateModel(
            name='LotMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='N° lot interne')),
                ('lot_fournisseur', models.CharField(blank=True, max_length=60, verbose_name='N° lot fournisseur')),
                ('date_reception', models.DateField(verbose_name='Date de réception')),
                ('date_peremption', models.DateField(blank=True, null=True, verbose_name='DLC / DLUO')),
                ('quantite_initiale', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantité reçue')),
                ('quantite_restante', models.DecimalField(decimal_places=3, editable=False, max_digits=14, verbose_name='Quantité restante')),
                ('statut', models.CharField(choices=[('A_CONTROLER', 'À contrôler (réception)'), ('LIBERE', 'Libéré'), ('BLOQUE', 'Bloqué'), ('EPUISE', 'Épuisé')], default='LIBERE', max_length=20, verbose_name='Statut')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots_matieres', to='referentiel.article', verbose_name='Article')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots_matieres', to='stocks.depot', verbose_name='Lieu de stockage')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots_livres', to='achats.fournisseur', verbose_name='Fournisseur')),
                ('ligne_reception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='achats.lignereceptionachat', verbose_name='Réception')),
            ],
            options={
                'verbose_name': 'Lot matière',
                'verbose_name_plural': 'Lots matières',
                'ordering': ['date_peremption', 'date_reception', 'pk'],
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
        migrations.CreateModel(
            name='TransfertStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='N° bon de transfert')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EXPEDIE', 'Expédié (en transit)'), ('RECU', 'Reçu'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_expedition', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expédition")),
                ('date_reception', models.DateTimeField(blank=True, null=True, verbose_name='Date de réception')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('depot_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_entrants', to='stocks.depot', verbose_name='Lieu de destination')),
                ('depot_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_sortants', to='stocks.depot', verbose_name='Lieu source')),
                ('expedie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferts_expedies', to=settings.AUTH_USER_MODEL, verbose_name='Expédié par')),
                ('recu_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferts_recus', to=settings.AUTH_USER_MODEL, verbose_name='Reçu par')),
            ],
            options={
                'verbose_name': 'Bon de transfert',
                'verbose_name_plural': 'Bons de transfert',
                'ordering': ['-date_creation'],
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
        migrations.CreateModel(
            name='LigneTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantité')),
                ('cout_unitaire', models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=14, null=True, verbose_name="Coût unitaire (à l'expédition)")),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.article', verbose_name='Article')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='qualite.lot', verbose_name='Lot')),
                ('transfert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stocks.transfertstock', verbose_name='Transfert')),
            ],
            options={
                'verbose_name': 'Ligne de transfert',
                'verbose_name_plural': 'Lignes de transfert',
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
    ]
