# Generated by Django 6.1 on 2026-10-07 12:30

import apps.core.validation
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0006_documents_pdf'),
        ('qualite', '0005_tracabilite_palettes_declencheurs'),
        ('stocks', '0004_depot_activite_depot_articles_autorises_depot_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=40, unique=True, verbose_name='Code')),
                ('designation', models.CharField(help_text='Ex : Allée A - Rack 2 - Niveau 1.', max_length=100, verbose_name='Désignation')),
                ('capacite_palettes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacité (palettes)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emplacements', to='stocks.depot', verbose_name='Lieu')),
            ],
            options={
                'verbose_name': 'Emplacement',
                'verbose_name_plural': 'Emplacements',
                'ordering': ['depot', 'code'],
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
        migrations.CreateModel(
            name='MouvementLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantité (+ entrée / - sortie)')),
                ('motif', models.CharField(max_length=200, verbose_name='Motif')),
                ('document_origine', models.CharField(blank=True, max_length=100, verbose_name='Document')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_lot', to='stocks.depot', verbose_name='Lieu')),
                ('ligne_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots_livres', to='commercial.lignecommande', verbose_name='Vente (ligne de commande)')),
                ('ligne_transfert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_lot', to='stocks.lignetransfert', verbose_name='Transfert')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_lot', to='qualite.lot', verbose_name='Lot')),
            ],
            options={
                'verbose_name': 'Mouvement de lot (produit fini)',
                'verbose_name_plural': 'Mouvements de lots (produits finis)',
                'ordering': ['date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='N° palette')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantité (unité de stock)')),
                ('statut', models.CharField(choices=[('EN_STOCK', 'En stock'), ('EN_TRANSIT', 'En transit'), ('EXPEDIEE', 'Expédiée / vendue')], default='EN_STOCK', max_length=12, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Constituée le')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Constituée par')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='palettes', to='stocks.depot', verbose_name='Lieu')),
                ('emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='palettes', to='stocks.emplacement', verbose_name='Emplacement')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='palettes', to='qualite.lot', verbose_name='Lot')),
            ],
            options={
                'verbose_name': 'Palette',
                'verbose_name_plural': 'Palettes',
                'ordering': ['-date_creation', 'numero'],
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
        migrations.AddField(
            model_name='lignetransfert',
            name='palette',
            field=models.ForeignKey(blank=True, help_text="Transfert d'une palette entière : article, lot et quantité sont repris de la palette.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_transfert', to='stocks.palette', verbose_name='Palette'),
        ),
    ]
