# Generated by Django 6.1 on 2026-08-23 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amortissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immobilisation', models.CharField(max_length=200, verbose_name='Immobilisation')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Valeur d'origine")),
                ('duree_amortissement_mois', models.PositiveIntegerField(verbose_name="Durée d'amortissement (mois)")),
                ('date_debut', models.DateField(verbose_name="Date de début d'amortissement")),
            ],
            options={
                'verbose_name': 'Amortissement',
                'verbose_name_plural': 'Amortissements',
            },
        ),
        migrations.CreateModel(
            name='CoutEnergie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_energie', models.CharField(choices=[('ELECTRICITE', 'Électricité'), ('EAU_CAPTAGE', 'Eau / captage-forage')], max_length=20, verbose_name="Type d'énergie")),
                ('periode', models.CharField(help_text='Format AAAA-MM', max_length=20, verbose_name='Période')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant de la charge')),
                ('cle_repartition', models.CharField(blank=True, help_text='Ex : au prorata des quantités produites, ou des heures machine.', max_length=100, verbose_name='Clé de répartition')),
            ],
            options={
                'verbose_name': "Coût d'énergie",
                'verbose_name_plural': "Coûts d'énergie",
            },
        ),
        migrations.CreateModel(
            name='CoutMainOeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Heures travaillées')),
                ('cout_horaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coût horaire')),
                ('ordre_fabrication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couts_main_oeuvre', to='production.ordrefabrication', verbose_name='Ordre de fabrication')),
            ],
            options={
                'verbose_name': "Coût main-d'œuvre",
                'verbose_name_plural': "Coûts main-d'œuvre",
            },
        ),
        migrations.CreateModel(
            name='CoutMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_unitaire', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Coût unitaire')),
                ('date_valorisation', models.DateField(verbose_name='Date de valorisation')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.article', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Coût matière',
                'verbose_name_plural': 'Coûts matières',
            },
        ),
        migrations.CreateModel(
            name='CoutReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_matiere_total', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Coût matières total')),
                ('cout_main_oeuvre_total', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name="Coût main-d'œuvre total")),
                ('cout_energie_total', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Coût énergie total')),
                ('cout_amortissement_total', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Coût amortissement total')),
                ('date_calcul', models.DateTimeField(auto_now=True, verbose_name='Date de calcul')),
                ('ordre_fabrication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cout_reel', to='production.ordrefabrication', verbose_name='Ordre de fabrication')),
            ],
            options={
                'verbose_name': 'Coût réel',
                'verbose_name_plural': 'Coûts réels',
            },
        ),
        migrations.CreateModel(
            name='CoutStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_standard_unitaire', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Coût standard unitaire')),
                ('date_debut_validite', models.DateField(verbose_name='Valide à partir du')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couts_standards', to='referentiel.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Coût standard',
                'verbose_name_plural': 'Coûts standards',
            },
        ),
    ]
