# Generated by Django 6.1 on 2026-10-06 21:39

import apps.core.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='N° charge')),
                ('periode', models.CharField(help_text='AAAA-MM', max_length=7, verbose_name='Période')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Montant')),
                ('statut_donnee', models.CharField(choices=[('REEL', 'Réel (mesuré / facturé)'), ('ESTIME', 'Estimé')], default='REEL', max_length=10, verbose_name='Donnée')),
                ('source', models.CharField(blank=True, help_text='Ex : facture SBEE n° 1234, relevé compteur, bulletin de paie.', max_length=200, verbose_name='Source')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('statut_repartition', models.CharField(choices=[('A_REPARTIR', 'À répartir'), ('REPARTIE', 'Répartie'), ('PARTIELLE', 'Partiellement répartie'), ('NON_REPARTIE', 'Non répartie (pas de clé défendable)')], default='A_REPARTIR', editable=False, max_length=15, verbose_name='Répartition')),
                ('motif_non_repartition', models.TextField(blank=True, editable=False, verbose_name='Motif de non-répartition')),
                ('date_saisie', models.DateTimeField(auto_now_add=True, verbose_name='Saisie le')),
            ],
            options={
                'verbose_name': 'Charge',
                'verbose_name_plural': 'Charges',
                'ordering': ['-periode', 'nature'],
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
        migrations.CreateModel(
            name='NatureCout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=150, verbose_name='Élément de coût')),
                ('categorie', models.CharField(choices=[('PRODUCTION', 'Coût de production'), ('STOCKAGE', 'Stockage produit fini (hors production)'), ('DISTRIBUTION', 'Distribution (hors production)'), ('HORS_COUT', 'Frais généraux non incorporés')], default='PRODUCTION', max_length=15, verbose_name='Catégorie')),
                ('categorie_economique', models.CharField(choices=[('ENERGIE', 'Énergie'), ('MAINTENANCE', 'Maintenance'), ('PIECES', 'Pièces de rechange / lubrifiants'), ('MAIN_OEUVRE', "Main-d'œuvre"), ('AMORTISSEMENT', 'Amortissement'), ('PRODUITS_TRAITEMENT', 'Produits de traitement / nettoyage / filtres'), ('ANALYSES', 'Analyses / laboratoire'), ('EMBALLAGES', 'Emballages / consommables'), ('LOCATION', 'Bâtiment / location'), ('CARBURANT', 'Carburant / péages'), ('SOUS_TRAITANCE', 'Sous-traitance'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Catégorie économique')),
                ('traitement', models.CharField(choices=[('DIRECT', 'Direct (identifiable sans clé)'), ('INDIRECT', 'Indirect (commun, réparti par clé)')], default='INDIRECT', max_length=10, verbose_name='Traitement')),
                ('inducteur', models.CharField(choices=[('VOLUME_EAU_M3', "Volume d'eau (m³)"), ('BOUTEILLES', 'Nombre de bouteilles / pots produits'), ('PACKS', 'Nombre de packs / cartons'), ('PALETTES', 'Nombre de palettes'), ('LITRES_PRODUITS', 'Litres produits'), ('HEURES_MACHINE', 'Heures machine'), ('HEURES_MO', "Heures de main-d'œuvre"), ('KWH', 'kWh'), ('ANALYSES_PONDEREES', 'Analyses pondérées'), ('PALETTES_JOURS', 'Palettes-jours (stockage)'), ('KM', 'Kilomètres (tournées)'), ('QUANTITE_LIVREE', 'Quantité livrée'), ('AUCUN', 'Aucun (charge directe uniquement)')], max_length=20, verbose_name='Clé / inducteur')),
                ('justification', models.TextField(blank=True, verbose_name='Justification de la clé')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Valide à partir du')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name="Valide jusqu'au")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Nature de coût (paramétrage)',
                'verbose_name_plural': 'Natures de coût (paramétrage)',
                'ordering': ['categorie', 'etape__ordre_reference', 'libelle'],
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
        migrations.CreateModel(
            name='RepartitionCout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('ACTIVITE', 'Activité'), ('OF', 'Ordre de fabrication'), ('PRODUIT', 'Produit / format'), ('ARTICLE', 'Produit (stockage / distribution)')], max_length=10, verbose_name='Niveau')),
                ('inducteur', models.CharField(choices=[('VOLUME_EAU_M3', "Volume d'eau (m³)"), ('BOUTEILLES', 'Nombre de bouteilles / pots produits'), ('PACKS', 'Nombre de packs / cartons'), ('PALETTES', 'Nombre de palettes'), ('LITRES_PRODUITS', 'Litres produits'), ('HEURES_MACHINE', 'Heures machine'), ('HEURES_MO', "Heures de main-d'œuvre"), ('KWH', 'kWh'), ('ANALYSES_PONDEREES', 'Analyses pondérées'), ('PALETTES_JOURS', 'Palettes-jours (stockage)'), ('KM', 'Kilomètres (tournées)'), ('QUANTITE_LIVREE', 'Quantité livrée'), ('AUCUN', 'Aucun (charge directe uniquement)')], max_length=20, verbose_name='Clé')),
                ('unite_cle', models.CharField(blank=True, max_length=30, verbose_name='Unité de la clé')),
                ('valeur_cle_totale', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Valeur totale de la clé')),
                ('valeur_cle_part', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Valeur de la clé pour ce niveau')),
                ('quote_part', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Quote-part')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Montant')),
                ('quantite_produite', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True, verbose_name='Quantité produite (unités de stock)')),
                ('cout_par_pack', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True, verbose_name='Coût par pack')),
                ('cout_par_unite', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True, verbose_name='Coût par bouteille / pot')),
                ('statut', models.CharField(choices=[('REEL', 'Réel'), ('ESTIME', 'Estimé'), ('REPARTI', 'Réparti')], max_length=10, verbose_name='Statut')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Source de la donnée')),
                ('justification', models.TextField(blank=True, verbose_name='Justification')),
                ('date_calcul', models.DateTimeField(auto_now_add=True, verbose_name='Calculé le')),
            ],
            options={
                'verbose_name': 'Répartition de coût',
                'verbose_name_plural': 'Répartitions de coûts (chaîne de calcul)',
                'ordering': ['charge', 'niveau', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='coutreel',
            name='cout_charges_reparties',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Charges de production rattachées à une étape puis réparties par inducteur jusqu'à cet OF.", max_digits=16, verbose_name='Charges imputées (cascade)'),
        ),
    ]
