# Generated by Django 6.1 on 2026-10-06 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couts', '0002_charge_naturecout_repartitioncout_and_more'),
        ('distribution', '0003_preparationlivraison_depot_and_more'),
        ('industriel', '0001_initial'),
        ('production', '0005_chiffrage_matieres'),
        ('referentiel', '0009_article_activite_article_activites_autorisees_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='activite',
            field=models.ForeignKey(blank=True, help_text="Vide = charge commune à plusieurs activités (répartie par l'inducteur).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='industriel.activite', verbose_name='Activité'),
        ),
        migrations.AddField(
            model_name='charge',
            name='equipement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='industriel.equipement', verbose_name='Équipement'),
        ),
        migrations.AddField(
            model_name='charge',
            name='ordre_fabrication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges_directes', to='production.ordrefabrication', verbose_name='OF (charge directe)'),
        ),
        migrations.AddField(
            model_name='charge',
            name='saisi_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par'),
        ),
        migrations.AddField(
            model_name='charge',
            name='tournee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='distribution.tournee', verbose_name='Tournée'),
        ),
        migrations.AddField(
            model_name='naturecout',
            name='etape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='natures_cout', to='industriel.etapestandard', verbose_name='Étape'),
        ),
        migrations.AddField(
            model_name='charge',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='couts.naturecout', verbose_name='Élément de coût'),
        ),
        migrations.AddField(
            model_name='repartitioncout',
            name='activite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='industriel.activite', verbose_name='Activité'),
        ),
        migrations.AddField(
            model_name='repartitioncout',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='referentiel.article', verbose_name='Produit / format'),
        ),
        migrations.AddField(
            model_name='repartitioncout',
            name='charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repartitions', to='couts.charge', verbose_name='Charge'),
        ),
        migrations.AddField(
            model_name='repartitioncout',
            name='etape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='industriel.etapestandard', verbose_name='Étape'),
        ),
        migrations.AddField(
            model_name='repartitioncout',
            name='ordre_fabrication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repartitions_couts', to='production.ordrefabrication', verbose_name='OF'),
        ),
        migrations.AddField(
            model_name='repartitioncout',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='couts.repartitioncout', verbose_name='Niveau supérieur'),
        ),
    ]
