# Generated by Django 6.1 on 2026-10-07 12:30

from django.db import migrations, models


def ajouter_natures_changement_serie(apps, schema_editor):
    """Éléments de coût du changement de série (document « Clés d'imputation », §7)."""
    NatureCout = apps.get_model("couts", "NatureCout")
    natures = [
        ("Arrêts de changement de série (main-d'œuvre et machine immobilisées)", "MAIN_OEUVRE", "INDIRECT",
         "TEMPS_CHANGEMENT_SERIE", "Charge rattachée à l'événement de changement de série : temps d'arrêt, nettoyage et réglage."),
        ("Nettoyage de changement de série", "PRODUITS_TRAITEMENT", "DIRECT", "AUCUN",
         "Direct à la série : coût réel saisi sur l'événement de changement de série."),
    ]
    rang = NatureCout.objects.count()
    for libelle, economique, traitement, inducteur, justification in natures:
        if NatureCout.objects.filter(libelle=libelle).exists():
            continue
        rang += 1
        while NatureCout.objects.filter(code=f"NAT-{rang:03d}").exists():
            rang += 1
        NatureCout.objects.create(
            code=f"NAT-{rang:03d}", libelle=libelle, categorie="PRODUCTION", categorie_economique=economique,
            traitement=traitement, inducteur=inducteur, justification=justification,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('couts', '0003_charge_activite_charge_equipement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturecout',
            name='inducteur',
            field=models.CharField(choices=[('VOLUME_EAU_M3', "Volume d'eau (m³)"), ('BOUTEILLES', 'Nombre de bouteilles / pots produits'), ('PACKS', 'Nombre de packs / cartons'), ('PALETTES', 'Nombre de palettes'), ('LITRES_PRODUITS', 'Litres produits'), ('HEURES_MACHINE', 'Heures machine'), ('HEURES_MO', "Heures de main-d'œuvre"), ('KWH', 'kWh'), ('ANALYSES_PONDEREES', 'Analyses pondérées'), ('TEMPS_CHANGEMENT_SERIE', 'Temps de changement de série (min)'), ('PALETTES_JOURS', 'Palettes-jours (stockage)'), ('KM', 'Kilomètres (tournées)'), ('QUANTITE_LIVREE', 'Quantité livrée'), ('AUCUN', 'Aucun (charge directe uniquement)')], max_length=30, verbose_name='Clé / inducteur'),
        ),
        migrations.AlterField(
            model_name='repartitioncout',
            name='inducteur',
            field=models.CharField(choices=[('VOLUME_EAU_M3', "Volume d'eau (m³)"), ('BOUTEILLES', 'Nombre de bouteilles / pots produits'), ('PACKS', 'Nombre de packs / cartons'), ('PALETTES', 'Nombre de palettes'), ('LITRES_PRODUITS', 'Litres produits'), ('HEURES_MACHINE', 'Heures machine'), ('HEURES_MO', "Heures de main-d'œuvre"), ('KWH', 'kWh'), ('ANALYSES_PONDEREES', 'Analyses pondérées'), ('TEMPS_CHANGEMENT_SERIE', 'Temps de changement de série (min)'), ('PALETTES_JOURS', 'Palettes-jours (stockage)'), ('KM', 'Kilomètres (tournées)'), ('QUANTITE_LIVREE', 'Quantité livrée'), ('AUCUN', 'Aucun (charge directe uniquement)')], max_length=30, verbose_name='Clé'),
        ),
        migrations.RunPython(ajouter_natures_changement_serie, migrations.RunPython.noop),
    ]
