# Generated by Django 6.1 on 2026-10-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couts', '0004_tracabilite_palettes_declencheurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturecout',
            name='inducteur',
            field=models.CharField(choices=[('VOLUME_EAU_M3', "Volume d'eau (m³)"), ('BOUTEILLES', 'Nombre de bouteilles / pots produits'), ('PACKS', 'Nombre de packs / cartons'), ('PALETTES', 'Nombre de palettes'), ('LITRES_PRODUITS', 'Litres produits'), ('HEURES_MACHINE', 'Heures machine'), ('HEURES_MO', "Heures de main-d'œuvre"), ('KWH', 'kWh'), ('ANALYSES_PONDEREES', 'Analyses pondérées'), ('TEMPS_CHANGEMENT_SERIE', 'Temps de changement de série (min)'), ('PALETTES_JOURS', 'Palettes-jours (stockage)'), ('KM', 'Kilomètres (tournées)'), ('QUANTITE_LIVREE', 'Quantité livrée'), ('PALETTES_LIVREES', 'Palettes livrées'), ('LITRES_LIVRES', 'Volume livré (litres)'), ('AUCUN', 'Aucun (charge directe uniquement)')], max_length=30, verbose_name='Clé / inducteur'),
        ),
        migrations.AlterField(
            model_name='repartitioncout',
            name='inducteur',
            field=models.CharField(choices=[('VOLUME_EAU_M3', "Volume d'eau (m³)"), ('BOUTEILLES', 'Nombre de bouteilles / pots produits'), ('PACKS', 'Nombre de packs / cartons'), ('PALETTES', 'Nombre de palettes'), ('LITRES_PRODUITS', 'Litres produits'), ('HEURES_MACHINE', 'Heures machine'), ('HEURES_MO', "Heures de main-d'œuvre"), ('KWH', 'kWh'), ('ANALYSES_PONDEREES', 'Analyses pondérées'), ('TEMPS_CHANGEMENT_SERIE', 'Temps de changement de série (min)'), ('PALETTES_JOURS', 'Palettes-jours (stockage)'), ('KM', 'Kilomètres (tournées)'), ('QUANTITE_LIVREE', 'Quantité livrée'), ('PALETTES_LIVREES', 'Palettes livrées'), ('LITRES_LIVRES', 'Volume livré (litres)'), ('AUCUN', 'Aucun (charge directe uniquement)')], max_length=30, verbose_name='Clé'),
        ),
    ]
