# Generated by Django 6.1.1 on 2026-09-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex : EV-FISC-JUS-10. Attribué manuellement (pas de numérotation automatique), il fait partie du paramétrage métier.', max_length=30, unique=True, verbose_name='Code fiscal')),
                ('famille_fiscale', models.CharField(help_text="Ex : 'Jus EVAM sucré/aromatisé'. Description métier de la nature fiscale, pas du produit commercial.", max_length=150, verbose_name='Famille fiscale')),
                ('exonere', models.BooleanField(default=False, help_text="Si coché, taux_tva n'est pas appliqué quel que soit son contenu (cas de l'eau minérale, sous condition de qualification officielle).", verbose_name='Exonéré de TVA')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=0, help_text="Ex : 18.00 pour 18%. Ignoré si 'Exonéré de TVA' est coché.", max_digits=5, verbose_name='Taux de TVA (%)')),
                ('taux_centimes_additionnels', models.DecimalField(decimal_places=2, default=0, help_text="Le document précise que ce taux s'applique sur le MONTANT DE TVA, pas sur le prix (ex : 5% de la TVA).", max_digits=5, verbose_name='Centimes additionnels (% de la TVA)')),
                ('taux_accise', models.DecimalField(decimal_places=2, default=0, help_text="S'applique sur le prix HT, AVANT le calcul de la TVA (l'accise entre dans la base de TVA - voir calculer_taxes()).", max_digits=5, verbose_name="Droit d'accises (%)")),
                ('sfec_actif', models.BooleanField(default=True, help_text='Si coché, les factures utilisant ce code fiscal doivent être transmises au SFEC pour certification.', verbose_name='Soumis à certification SFEC')),
                ('situation', models.TextField(blank=True, help_text="Ex : 'Qualification eau minérale EVAM à confirmer' - traçabilité des réserves ou conditions du document source.", verbose_name='Situation / commentaire')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Code fiscal',
                'verbose_name_plural': 'Codes fiscaux (matrice fiscale)',
                'ordering': ['code'],
            },
        ),
    ]