# Generated by Django 6.1 on 2026-09-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalite', '0002_famille_fiscale_liste_deroulante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codefiscal',
            name='code',
            field=models.CharField(editable=False, help_text="Généré automatiquement : EV-FISC-{famille}-{EXO | taux d'accise | taux de TVA}, ex : EV-FISC-JUS-10. Jamais saisi.", max_length=30, unique=True, verbose_name='Code fiscal'),
        ),
    ]
