# Generated by Django 6.1 on 2026-09-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalite', '0003_codification_automatique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codefiscal',
            name='code',
            field=models.CharField(editable=False, help_text='Généré automatiquement : EV-FISC-{produit}-{taux de TVA}, ex : EV-FISC-YAO-18, EV-FISC-EAU-0 (exonéré). Jamais saisi.', max_length=30, unique=True, verbose_name='Code fiscal'),
        ),
    ]
