# Generated by Django 6.1 on 2026-08-23 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code client')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom / Raison sociale')),
                ('type_client', models.CharField(choices=[('PARTICULIER', 'Particulier'), ('SOCIETE', 'Société'), ('CONTRAT', 'Client sous contrat')], max_length=20, verbose_name='Type de client')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('encours_autorise', models.DecimalField(decimal_places=2, default=0, help_text='Montant maximum de créance tolérée avant blocage des commandes.', max_digits=14, verbose_name='Encours autorisé')),
                ('bloque', models.BooleanField(default=False, verbose_name='Compte bloqué')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='ContratClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('conditions', models.TextField(blank=True, verbose_name='Conditions particulières')),
            ],
            options={
                'verbose_name': 'Contrat client',
                'verbose_name_plural': 'Contrats clients',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant total')),
                ('statut', models.CharField(choices=[('EMISE', 'Émise'), ('PAYEE', 'Payée'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée'), ('ANNULEE', 'Annulée')], default='EMISE', max_length=25, verbose_name='Statut')),
                ('date_emission', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Prix unitaire')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('contact', models.CharField(blank=True, max_length=150, verbose_name='Contact')),
                ('statut', models.CharField(default='Nouveau', max_length=50, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Prospect',
                'verbose_name_plural': 'Prospects',
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Prix unitaire')),
                ('date_debut_validite', models.DateField(verbose_name='Valide à partir du')),
                ('date_fin_validite', models.DateField(blank=True, null=True, verbose_name="Valide jusqu'au")),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifs',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro')),
                ('type_commande', models.CharField(choices=[('COMPTANT', 'Vente au comptant'), ('CONTRAT', 'Client sous contrat')], max_length=15, verbose_name='Type de commande')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('EN_PREPARATION', 'En préparation'), ('LIVREE', 'Livrée'), ('FACTUREE', 'Facturée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('date_commande', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='commercial.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_commande'],
            },
        ),
    ]
