# Generated by Django 6.1 on 2026-08-23 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0001_initial'),
        ('referentiel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='cree_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Créée par'),
        ),
        migrations.AddField(
            model_name='contratclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='commercial.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commercial.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='facture',
            name='commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='facture', to='commercial.commande', verbose_name='Commande'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.article', verbose_name='Article'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commercial.commande', verbose_name='Commande'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.article', verbose_name='Article'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Laisser vide pour un tarif public standard.', null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.client', verbose_name='Client (tarif spécifique)'),
        ),
    ]
