# Generated by Django 6.1.1 on 2026-09-15 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_initial'),
        ('fiscalite', '0001_initial'),
        ('referentiel', '0002_article_activite_analytique_article_centre_cout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='montant_ht_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant total HT'),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_taxes_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Somme accise + TVA + centimes additionnels de toutes les lignes.', max_digits=14, verbose_name='Montant total des taxes'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant total TTC'),
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Prix unitaire HT')),
                ('taux_tva_applique', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux de TVA appliqué (%)')),
                ('taux_accise_applique', models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Taux d'accise appliqué (%)")),
                ('taux_centimes_applique', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux de centimes additionnels appliqué (%)')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant HT')),
                ('montant_accise', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant accise')),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant TVA')),
                ('montant_centimes', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant centimes additionnels')),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant TTC')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.article', verbose_name='Article')),
                ('code_fiscal', models.ForeignKey(help_text='Référence du code fiscal au moment de la facturation (traçabilité).', on_delete=django.db.models.deletion.PROTECT, to='fiscalite.codefiscal', verbose_name='Code fiscal utilisé')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_facture', to='commercial.facture', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
            },
        ),
    ]