# Generated by Django 6.1.1 on 2026-09-16 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0003_facture_montant_ht_total_facture_montant_taxes_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='delai_paiement_jours',
            field=models.PositiveIntegerField(default=0, help_text="0 = paiement immédiat (comptant). Sert à calculer l'échéance des factures.", verbose_name='Délai de paiement (jours)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_echeance',
            field=models.DateField(blank=True, help_text="Calculée automatiquement à la création (date d'émission + délai de paiement du client).", null=True, verbose_name="Date d'échéance"),
        ),
        migrations.CreateModel(
            name='Avoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Montant de l'avoir")),
                ('motif', models.TextField(verbose_name='Motif')),
                ('statut', models.CharField(choices=[('EMIS', 'Émis'), ('UTILISE', 'Utilisé'), ('ANNULE', 'Annulé')], default='EMIS', max_length=15, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_utilisation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'utilisation")),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avoirs', to='commercial.client', verbose_name='Client')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('facture_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avoirs_emis', to='commercial.facture', verbose_name="Facture d'origine")),
                ('facture_utilisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avoirs_utilises', to='commercial.facture', verbose_name="Facture d'utilisation")),
            ],
            options={
                'verbose_name': 'Avoir',
                'verbose_name_plural': 'Avoirs',
                'ordering': ['-date_creation'],
            },
        ),
    ]