# Generated by Django 6.1 on 2026-09-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0004_client_delai_paiement_jours_facture_date_echeance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(editable=False, help_text='Généré automatiquement (CLI-000001...), jamais saisi.', max_length=30, unique=True, verbose_name='Code client'),
        ),
    ]
