# Generated by Django 6.1 on 2026-10-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_codification_automatique'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ifu',
            field=models.CharField(blank=True, help_text='Identifiant fiscal du client (imprimé sur ses factures).', max_length=30, verbose_name='IFU'),
        ),
    ]
