# Generated by Django 6.1 on 2026-10-07 19:56

import apps.core.validation
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0006_documents_pdf'),
        ('referentiel', '0009_article_activite_article_activites_autorisees_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='derogation_autorisee_par',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derogations_prix', to=settings.AUTH_USER_MODEL, verbose_name='Dérogation autorisée par'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='motif_derogation',
            field=models.CharField(blank=True, help_text='Obligatoire si le prix diffère du tarif (client sous contrat uniquement).', max_length=255, verbose_name='Motif de la dérogation de prix'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='prix_tarif',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=14, null=True, verbose_name='Prix du tarif'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='tarif',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='commercial.tarif', verbose_name='Tarif appliqué'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='contrat',
            field=models.ForeignKey(blank=True, help_text='Tarif négocié dans un contrat (prioritaire sur le tarif client et le tarif public).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='commercial.contratclient', verbose_name='Contrat'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='prix_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Repris automatiquement du tarif en vigueur (contrat, client ou public) : le prix est imposé.', max_digits=14, verbose_name='Prix unitaire'),
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='N° devis')),
                ('type_commande', models.CharField(choices=[('COMPTANT', 'Vente au comptant'), ('CONTRAT', 'Client sous contrat')], default='COMPTANT', max_length=15, verbose_name='Type de vente')),
                ('date_validite', models.DateField(verbose_name="Valable jusqu'au")),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé au client'), ('ACCEPTE', 'Accepté'), ('PARTIELLEMENT_ACCEPTE', 'Accepté partiellement'), ('REFUSE', 'Refusé'), ('EXPIRE', 'Expiré')], default='BROUILLON', max_length=25, verbose_name='Statut')),
                ('conditions', models.TextField(blank=True, verbose_name='Conditions / remarques')),
                ('motif_refus', models.TextField(blank=True, verbose_name='Motif du refus')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Réponse du client le')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis', to='commercial.client', verbose_name='Client')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis_crees', to=settings.AUTH_USER_MODEL, verbose_name='Établi par')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-date_creation'],
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
        migrations.AddField(
            model_name='commande',
            name='devis',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='commercial.devis', verbose_name="Devis d'origine"),
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=14, verbose_name='Prix unitaire HT')),
                ('prix_tarif', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=14, null=True, verbose_name='Prix du tarif')),
                ('motif_derogation', models.CharField(blank=True, max_length=255, verbose_name='Motif de la dérogation de prix')),
                ('quantite_acceptee', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=12, null=True, verbose_name='Quantité acceptée')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.article', verbose_name='Article')),
                ('derogation_autorisee_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Dérogation autorisée par')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commercial.devis', verbose_name='Devis')),
                ('tarif', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='commercial.tarif', verbose_name='Tarif appliqué')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'verbose_name_plural': 'Lignes de devis',
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
    ]
