# Generated by Django 6.1 on 2026-10-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0007_devis_tarifs_contrats'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='sfec_code',
            field=models.CharField(blank=True, editable=False, max_length=80, verbose_name='Code de certification (MECeF)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='sfec_compteurs',
            field=models.CharField(blank=True, editable=False, max_length=80, verbose_name='Compteurs SFEC'),
        ),
        migrations.AddField(
            model_name='facture',
            name='sfec_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Certifiée le'),
        ),
        migrations.AddField(
            model_name='facture',
            name='sfec_message',
            field=models.TextField(blank=True, editable=False, verbose_name='Dernier message SFEC'),
        ),
        migrations.AddField(
            model_name='facture',
            name='sfec_nim',
            field=models.CharField(blank=True, editable=False, max_length=40, verbose_name='NIM (n° machine)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='sfec_qr',
            field=models.TextField(blank=True, editable=False, verbose_name='Contenu du QR code'),
        ),
        migrations.AddField(
            model_name='facture',
            name='sfec_statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'Non certifiée'), ('CERTIFIEE', 'Certifiée'), ('ERREUR', 'Erreur de certification')], default='EN_ATTENTE', editable=False, max_length=12, verbose_name='Certification SFEC'),
        ),
    ]
