# Generated by Django 6.1 on 2026-10-06 21:39

import apps.core.validation
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiel', '0008_chiffrage_matieres'),
        ('stocks', '0003_valorisation_cmup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, help_text='Généré automatiquement depuis la désignation (EAU, JUS, YAOURT).', max_length=20, unique=True, verbose_name='Code activité')),
                ('designation', models.CharField(max_length=100, unique=True, verbose_name='Désignation')),
                ('regles_specifiques', models.TextField(blank=True, verbose_name='Règles spécifiques')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['code'],
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
        migrations.CreateModel(
            name='EtapeStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code étape')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
                ('phase', models.CharField(choices=[('AMONT', 'Eau : captage, traitement, stockage process'), ('PREPARATION', 'Préparation du produit'), ('CONDITIONNEMENT', 'Remplissage et conditionnement'), ('APRES_PRODUCTION', 'Après production (hors coût de production)')], default='CONDITIONNEMENT', max_length=20, verbose_name='Phase')),
                ('ordre_reference', models.PositiveIntegerField(default=0, verbose_name='Ordre dans le circuit de référence')),
                ('description', models.TextField(blank=True, verbose_name='Ce qui se passe à cette étape')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('sous_etape_de', models.ForeignKey(blank=True, help_text="Ex : Décantation, Filtration, Cuve tampon et UV détaillent le Traitement de l'eau.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sous_etapes', to='industriel.etapestandard', verbose_name='Sous-étape de')),
            ],
            options={
                'verbose_name': 'Étape standard',
                'verbose_name_plural': 'Étapes standard',
                'ordering': ['ordre_reference', 'code'],
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Code ligne')),
                ('designation', models.CharField(max_length=100, verbose_name='Désignation')),
                ('cadence_nominale', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Capacité / cadence')),
                ('unite_cadence', models.CharField(blank=True, help_text='Ex : bouteilles/heure.', max_length=30, verbose_name='Unité de cadence')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='industriel.activite', verbose_name='Activité')),
                ('formats_compatibles', models.ManyToManyField(blank=True, help_text="Vide = tous les formats de l'activité.", related_name='lignes_compatibles', to='referentiel.article', verbose_name='Formats compatibles')),
            ],
            options={
                'verbose_name': 'Ligne de production',
                'verbose_name_plural': 'Lignes de production',
                'ordering': ['code'],
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Code circuit')),
                ('designation', models.CharField(max_length=150, verbose_name='Désignation')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('ARCHIVE', 'Remplacé / archivé')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circuits', to='industriel.activite', verbose_name='Activité')),
                ('article', models.ForeignKey(blank=True, help_text="Vide = tous les formats de l'activité.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='circuits', to='referentiel.article', verbose_name='Produit / format')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='circuits_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('ligne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='circuits', to='industriel.ligne', verbose_name='Ligne')),
            ],
            options={
                'verbose_name': 'Circuit de production',
                'verbose_name_plural': 'Circuits de production',
                'ordering': ['activite', 'code', '-version'],
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=40, unique=True, verbose_name='Code poste')),
                ('designation', models.CharField(blank=True, max_length=100, verbose_name='Désignation')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre sur la ligne')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postes', to='industriel.etapestandard', verbose_name='Fonction / étape')),
                ('formats_compatibles', models.ManyToManyField(blank=True, help_text='Vide = les formats de la ligne.', related_name='postes_compatibles', to='referentiel.article', verbose_name='Formats compatibles')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postes', to='industriel.ligne', verbose_name='Ligne')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'ordering': ['ligne', 'ordre'],
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
        migrations.CreateModel(
            name='Usine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Code usine')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('localisation', models.CharField(blank=True, max_length=255, verbose_name='Adresse / localisation')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('activites', models.ManyToManyField(blank=True, related_name='usines', to='industriel.activite', verbose_name='Activités produites')),
                ('magasin_matieres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usines_magasin', to='stocks.depot', verbose_name="Magasin matières de l'usine")),
                ('stock_produits_finis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usines_stock_pf', to='stocks.depot', verbose_name="Stock produits finis de l'usine")),
            ],
            options={
                'verbose_name': 'Usine',
                'verbose_name_plural': 'Usines',
                'ordering': ['code'],
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
        migrations.AddField(
            model_name='ligne',
            name='usine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='industriel.usine', verbose_name='Usine'),
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Code machine')),
                ('designation', models.CharField(max_length=100, verbose_name='Désignation')),
                ('type_equipement', models.CharField(choices=[('FORAGE', 'Forage / captage'), ('POMPE', 'Pompe'), ('TRAITEMENT', "Traitement de l'eau (filtre, UV...)"), ('CUVE', 'Cuve'), ('MELANGEUR', 'Mélangeur / cuve de préparation'), ('PASTEURISATEUR', 'Pasteurisateur / traitement thermique'), ('SOUFFLEUSE', 'Souffleuse'), ('REMPLISSEUSE', 'Remplisseuse'), ('BOUCHEUSE', 'Boucheuse / operculeuse'), ('ETIQUETEUSE', 'Étiqueteuse'), ('FARDELEUSE', 'Fardeleuse / plastification'), ('PALETTISEUR', 'Palettiseur / filmeuse palette'), ('LABORATOIRE', 'Équipement de laboratoire'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type')),
                ('cadence_nominale', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Capacité / cadence')),
                ('unite_cadence', models.CharField(blank=True, max_length=30, verbose_name='Unité de cadence')),
                ('compteur_energie', models.BooleanField(default=False, verbose_name="Compteur d'énergie (kWh) disponible")),
                ('compteur_heures', models.BooleanField(default=False, verbose_name="Compteur d'heures de marche disponible")),
                ('compteur_pieces', models.BooleanField(default=False, verbose_name='Compteur de pièces disponible')),
                ('compteur_volume', models.BooleanField(default=False, verbose_name='Débitmètre / compteur de volume disponible')),
                ('valeur_acquisition', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name="Valeur d'acquisition")),
                ('duree_amortissement_mois', models.PositiveIntegerField(blank=True, null=True, verbose_name="Durée d'amortissement (mois)")),
                ('date_mise_en_service', models.DateField(blank=True, null=True, verbose_name='Date de mise en service')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('activite', models.ForeignKey(blank=True, help_text='Vide = équipement commun à plusieurs activités.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipements', to='industriel.activite', verbose_name='Activité dédiée')),
                ('formats_compatibles', models.ManyToManyField(blank=True, related_name='equipements_compatibles', to='referentiel.article', verbose_name='Formats compatibles')),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipements', to='industriel.poste', verbose_name='Poste')),
                ('usine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipements', to='industriel.usine', verbose_name='Usine')),
            ],
            options={
                'verbose_name': 'Machine / équipement',
                'verbose_name_plural': 'Machines / équipements',
                'ordering': ['code'],
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
        migrations.CreateModel(
            name='EtapeCircuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(verbose_name='Ordre')),
                ('obligatoire', models.BooleanField(default=True, help_text="Ex : le soufflage n'existe que si la bouteille est soufflée sur site.", verbose_name='Obligatoire')),
                ('temps_theorique_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Temps théorique (min)')),
                ('perte_theorique_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Perte théorique (%)')),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='industriel.circuit', verbose_name='Circuit')),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='industriel.equipement', verbose_name='Machine')),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utilisations', to='industriel.etapestandard', verbose_name='Étape')),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='industriel.poste', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Étape de circuit',
                'verbose_name_plural': 'Étapes de circuit',
                'ordering': ['circuit', 'ordre'],
                'unique_together': {('circuit', 'etape'), ('circuit', 'ordre')},
            },
            bases=(apps.core.validation.ValidationAvantEnregistrement, models.Model),
        ),
    ]
