# Generated by Django 6.1 on 2026-10-07 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industriel', '0002_parametrage_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='inducteur_amortissement',
            field=models.CharField(blank=True, help_text="Clé d'imputation de l'amortissement selon l'usage réel (m³ d'eau, heures machine, bouteilles, packs...). Vide = volume d'eau en amont, heures machine ailleurs.", max_length=30, verbose_name="Inducteur d'amortissement"),
        ),
        migrations.AddField(
            model_name='equipement',
            name='postes_supplementaires',
            field=models.ManyToManyField(blank=True, help_text='Machine combinée (ex : remplissage + bouchage) : modélisée une seule fois, rattachée à tous ses postes.', related_name='equipements_secondaires', to='industriel.poste', verbose_name='Autres postes réalisés'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipements', to='industriel.poste', verbose_name='Poste principal'),
        ),
    ]
