# Generated by Django 6.1.1 on 2026-09-16 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0003_facture_montant_ht_total_facture_montant_taxes_total_and_more'),
        ('distribution', '0001_initial'),
        ('qualite', '0001_initial'),
        ('referentiel', '0002_article_activite_analytique_article_centre_cout_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleRetour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat', models.CharField(choices=[('RECUPERABLE_DIRECT', 'Récupérable directement'), ('RECUPERABLE_AVEC_INTERVENTION', 'Récupérable avec intervention'), ('NON_RECUPERABLE', 'Non récupérable')], max_length=30, verbose_name='Résultat')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date_controle', models.DateTimeField(auto_now_add=True, verbose_name='Date de contrôle')),
                ('controle_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Contrôlé par')),
            ],
            options={
                'verbose_name': 'Contrôle de retour',
                'verbose_name_plural': 'Contrôles de retours',
            },
        ),
        migrations.CreateModel(
            name='ReclamationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='N° réclamation')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité concernée')),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Prix unitaire (repris de la facture)')),
                ('type_probleme', models.CharField(choices=[('PRODUIT_DEFECTUEUX', 'Produit défectueux'), ('PRODUIT_MANQUANT', 'Produit manquant'), ('ERREUR_REFERENCE', 'Erreur de référence livrée'), ('EMBALLAGE_ENDOMMAGE', 'Emballage endommagé'), ('PRODUIT_PERIME', 'Produit périmé'), ('AUTRE', 'Autre')], max_length=30, verbose_name='Type de problème')),
                ('description', models.TextField(verbose_name='Description')),
                ('produit_retourne', models.BooleanField(default=False, help_text='Si oui, un RetourPhysique doit être créé pour cette réclamation.', verbose_name='Le client a-t-il ramené le produit ?')),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('EN_COURS', 'En cours'), ('CLOTUREE', 'Clôturée')], default='OUVERTE', max_length=15, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_cloture', models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.article', verbose_name='Produit concerné')),
                ('bon_livraison', models.ForeignKey(blank=True, help_text="Recherche du BL - laisser vide si le BL n'a pas pu être retrouvé.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to='distribution.bonlivraison', verbose_name='Bon de livraison')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to='commercial.client', verbose_name='Client')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='commercial.facture', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Réclamation client',
                'verbose_name_plural': 'Réclamations clients',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CoutRetourPerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_detruite', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Quantité détruite')),
                ('cout_produit_detruit', models.DecimalField(blank=True, decimal_places=2, help_text="À valoriser manuellement (dernier coût de revient connu de l'article).", max_digits=14, null=True, verbose_name='Coût du produit détruit')),
                ('cout_reconditionnement', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Coût du reconditionnement')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('reclamation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cout_retour_perte', to='reclamations.reclamationclient', verbose_name='Réclamation')),
            ],
            options={
                'verbose_name': 'Coût de retour / perte',
                'verbose_name_plural': 'Coûts de retours / pertes',
            },
        ),
        migrations.CreateModel(
            name='Reconditionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name="Description de l'intervention")),
                ('quantite_reconditionnee', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Quantité reconditionnée')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=15, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('controle_retour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconditionnement', to='reclamations.controleretour', verbose_name='Contrôle de retour')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': 'Reconditionnement',
                'verbose_name_plural': 'Reconditionnements',
            },
        ),
        migrations.CreateModel(
            name='RetourPhysique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_retournee', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité retournée')),
                ('statut', models.CharField(choices=[('EN_QUARANTAINE', 'En quarantaine'), ('CONTROLE_EFFECTUE', 'Contrôle effectué')], default='EN_QUARANTAINE', max_length=20, verbose_name='Statut')),
                ('date_reception', models.DateTimeField(auto_now_add=True, verbose_name='Date de réception')),
                ('lot', models.ForeignKey(blank=True, help_text='Traçabilité par lot (règle clé n°4 du circuit).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='qualite.lot', verbose_name="Lot d'origine")),
                ('receptionne_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Réceptionné par')),
                ('reclamation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retour_physique', to='reclamations.reclamationclient', verbose_name='Réclamation')),
            ],
            options={
                'verbose_name': 'Retour physique',
                'verbose_name_plural': 'Retours physiques',
            },
        ),
        migrations.AddField(
            model_name='controleretour',
            name='retour_physique',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controle', to='reclamations.retourphysique', verbose_name='Retour physique'),
        ),
        migrations.CreateModel(
            name='SolutionClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_solution', models.CharField(choices=[('REMPLACEMENT', 'Remplacement'), ('AVOIR', 'Avoir'), ('REMBOURSEMENT', 'Remboursement')], max_length=15, verbose_name='Type de solution')),
                ('montant_avoir', models.DecimalField(blank=True, decimal_places=2, help_text='Crédit sur prochaine commande ou facture.', max_digits=14, null=True, verbose_name="Montant de l'avoir")),
                ('montant_rembourse', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Montant remboursé')),
                ('reference_sortie_caisse', models.CharField(blank=True, help_text="À renseigner manuellement en l'absence d'un module Décaissement dédié (voir README).", max_length=100, verbose_name='Référence de la sortie de caisse')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('autorise_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Autorisé par')),
                ('nouvelle_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplacement_de_reclamations', to='commercial.commande', verbose_name='Nouvelle commande (remplacement)')),
                ('reclamation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='reclamations.reclamationclient', verbose_name='Réclamation')),
            ],
            options={
                'verbose_name': 'Solution apportée au client',
                'verbose_name_plural': 'Solutions apportées aux clients',
            },
        ),
    ]